### ISSUE TITLE
[Bug]: Dump window opens automatically

### ISSUE THREAD

**Issue by jjcsinke** [beyondcode/herd-community#1017] opened 2024-09-20 11:47 UTC
### Platform

macOS

### Operating system version

macOS 15.0

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.0 build 33

### PHP Version

N/A

### Bug description

The dump window opens automatically and does not stay closed when I click the red close button. 

### Steps to reproduce

Run something Laravel, like artisan queue:work (does not need jobs on my end)
Open dump window once? (Didn't notice this before)
Close dump window
See it re-open. (see attached screen recording) 
https://github.com/user-attachments/assets/51ea7524-38ab-49ad-8d61-7462834dd95a

It only does it when Laravel is running, either frontend calls or empty queue (no incoming dumps or logs)
Does not matter if intercept is enabled or not, and also does it with all topics disabled in the dump window settings. 
### Relevant log output

```shell
Not sure how to get this.
```

**Comment by mpociot** [comment] 2024-09-24 12:33
Does this depend on a specific thing happening in your app, or can you reproduce this with a blank Laravel app created via `laravel new` as well?

**Comment by jjcsinke** [comment] 2024-09-24 13:41
Sorry I can't seem to reproduce it here anymore. 
Probably was something on my end, had a failing closure in our queue, but strange that it would open without messages.

**Comment by jjcsinke** [comment] 2024-09-24 13:49
Oh it now does it again on the clean project.

**Comment by mpociot** [comment] 2024-09-24 19:21
Ohh now I get it.
So the problem is that the queue worker was started while dump interception/query interception was still enabled. 
Because of this, the CLI process still collects the queries and sends them to the UI.

I'd close this as this is not necessarily a "bug", but it's something that we need to explain a bit better in the UI.

**Closed by mpociot** 2024-09-24 19:21 UTC
Labels: needs more information, macOS
