### ISSUE TITLE
[Bug]: problem executing php artisan serve command

### ISSUE THREAD

**Issue by danielAntonio3** [beyondcode/herd-community#839] opened 2024-06-25 03:50 UTC
### Platform

Windows

### Operating system version

windows 11

### System architecture

Intel (x86)

### Herd Version

1.7.2

### PHP Version

8.1

### Bug description

When I execute the php artisan serve command, the server tries to wake up and tells me that the port is already busy but it is actually free.

### Steps to reproduce

I simply run the PHP artisan serve command

### Relevant log output

```shell
Starting Laravel development server: http://127.0.0.1:8000
[Mon Jun 24 21:36:05 2024] Failed to listen on 127.0.0.1:8000 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8001
[Mon Jun 24 21:36:05 2024] Failed to listen on 127.0.0.1:8001 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8002
[Mon Jun 24 21:36:06 2024] Failed to listen on 127.0.0.1:8002 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8003
[Mon Jun 24 21:36:06 2024] Failed to listen on 127.0.0.1:8003 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8004
[Mon Jun 24 21:36:07 2024] Failed to listen on 127.0.0.1:8004 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8005
[Mon Jun 24 21:36:07 2024] Failed to listen on 127.0.0.1:8005 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8006
[Mon Jun 24 21:36:08 2024] Failed to listen on 127.0.0.1:8006 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8007
[Mon Jun 24 21:36:08 2024] Failed to listen on 127.0.0.1:8007 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8008
[Mon Jun 24 21:36:09 2024] Failed to listen on 127.0.0.1:8008 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8009
[Mon Jun 24 21:36:10 2024] Failed to listen on 127.0.0.1:8009 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8010
[Mon Jun 24 21:36:10 2024] Failed to listen on 127.0.0.1:8010 (reason: ?)
```

**Comment by mpociot** [comment] 2024-06-25 15:01
This is a duplicate of https://github.com/beyondcode/herd-community/issues/737
But you should just visit http://FOLDERNAME.test instead of using artisan serve

**Closed by mpociot** 2024-06-25 15:01 UTC
Labels: windows
