### ISSUE TITLE
[Bug]: Frequent 504 Errors After Updating to Latest Version

### ISSUE THREAD

**Issue by mauriciodulce** [beyondcode/herd-community#1077] opened 2024-10-08 21:37 UTC
### Platform

macOS

### Operating system version

14.7 (23H124)

### System architecture

Intel (x86)

### Herd Version

1.11.1 Build 34

### PHP Version

PHP 8.3.12 (cli) (built: Sep 27 2024 00:34:25) (NTS)

### Bug description

Hello, is anyone having issues with Herd Pro? I updated to the latest version today, and it’s returning many 502 errors or simply stops responding, forcing me to restart it. It works fine for about 3 minutes and then starts causing problems again. Any suggestions on how to fix this?

**Comment by mpociot** [comment] 2024-10-09 15:02
I'm closing this one as we discussed this via Google Meet.
It seems like this error was caused by SPX / the profiler being enabled.

**Closed by mpociot** 2024-10-09 15:02 UTC
Labels: macOS
