### ISSUE TITLE
[Bug]: Create Site via GUI stuck

### ISSUE THREAD

**Issue by mariusmihai112** [beyondcode/herd-community#1081] opened 2024-10-10 10:22 UTC
### Platform

macOS

### Operating system version

macOS Sonoma 14.1.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1

### PHP Version

8.3.12

### Bug description

The modal listing the choices I can make to create a site appears and disappears in a loop.

https://github.com/user-attachments/assets/fc50ce00-85b8-489c-8df4-805edb539543

### Steps to reproduce

1. Open Herd
2. Select **Sites** from the menu
3. Press **Add Site**

**Comment by mpociot** [comment] 2024-10-10 10:25
I'll close this as it's a duplicate of #1052

**Closed by mpociot** 2024-10-10 10:25 UTC
Labels: macOS
