### ISSUE TITLE
[Bug]: openssl extension doesn't work

### ISSUE THREAD

**Issue by deleugpn** [beyondcode/herd-community#148] opened 2023-08-27 20:49 UTC
### Operating system version

13.4.1 (c) (22F770820d)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0 (Build: 14)

### PHP Version

PHP 8.2.9 (cli) (built: Aug 22 2023 13:42:30) (NTS)

### Bug description

Openssl extensions are not working due to some lack of connection with the system library.

### Steps to reproduce

php -a
Interactive shell

php > var_dump(openssl_pkey_new());
bool(false)

php > var_dump(openssl_error_string());
string(64) "error:FFFFFFFF80000002:system library::No such file or directory"

### Relevant log output

```shell
string(64) "error:FFFFFFFF80000002:system library::No such file or directory"
```

**Comment by mpociot** [comment] 2023-08-30 08:19
Thanks for reporting this.
The issue is that Herd's PHP binary does include OpenSSL, but it does not include the `openssl.cnf` file which is required for these methods to work (see [the PHP documentation]()).

You can fix this locally by manually downloading the openssl.cnf file from the OpenSSL repository: https://github.com/openssl/openssl/blob/bd3b026faab3b5ee5aa6b52ba6eb4080bc144b28/apps/openssl.cnf#L4

Store this for example in your ~/Library/Application Support/Herd/config/php directory and add the following environment variable to your bashrc/zshrc file:

OPENSSL_CONF=/Users/[YOUR-USERNAME]/Library/Application Support/Herd/config/php/openssl.cnf

This fixes the issue when using PHP via the CLI.

In order to fix this via FPM, we will need to modify Herd.
I'll leave this issue open so that we can close it once this has been added in the next update.

**Comment by pxlrbt** [comment] 2023-09-01 07:16
Maybe stuff like this can be added to the Troubleshooting section on the docs as "Known issue" or similar when there is an existing workaround?

**Comment by dasundev** [comment] 2023-09-09 17:05
After searching for some time, I found this issue that helped me understand why I couldn't fix this error on my own. 

@mpociot I believe this issue will be resolved soon because I'm using Laravel Herd for my development. 

However, I've had to temporarily stop working on my project until the issue is fixed.

**Comment by deleugpn** [comment] 2023-10-08 23:56
Just one additional note. It might be good if Herd could try or default to `/etc/ssl/openssl.cnf`. I have OpenSSL installed locally and the configuration is already available there. All I had to do was `OPENSSL_CONF=/etc/ssl/openssl.cnf php artisan` and it worked. It seems like a better default than the `/ssl/openssl.cnf` that ships with Herd given this is a Macbook application.

**Comment by p4bl1t0** [comment] 2023-10-26 19:45
Have anyone find a workaround to fill FPM herd with an OpenSSL cnf file?

**Comment by dasundev** [comment] 2023-10-27 06:50
@p4bl1t0 Still waiting for the Herd update.

**Comment by p4bl1t0** [comment] 2023-10-27 15:00
@mpociot are there any update? Or can you help us to find a workaround?

I'm not able to create the /ssl/openssl.cnf because /ssl doesn't exist and / is read-only.

**Comment by Log1x** [comment] 2023-10-31 00:07
Can the path just get changed to `/etc/ssl/openssl.cnf` for FPM and CLI for now? No possible workaround for FPM is a little painful.

**Comment by SaaberDev** [comment] 2023-11-14 11:05
@mpociot 

is there any way to use it from homebrew for now ?

**Comment by pxlrbt** [comment] 2023-11-27 16:54
I copied the `openssl.conf` and set the env var, but I am still getting an error for `artisan package:discover`:

```
file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A000086:SSL routines::certificate verify failed
```

Because of this lines:

```
 at app/Console/Kernel.php:46
     42▕      */
     43▕     protected function schedule(Schedule $schedule): void
     44▕     {
     45▕         if (app()->environment('production')) {
  ➜  46▕             file_get_contents('https://cronitor.link/p/xxx/yyyy');
```

**Closed** 2023-12-11 14:09 UTC

**Comment by dasundev** [comment] 2023-12-11 14:30
@mpociot Thanks! ♥️

**Comment by sander3** [comment] 2023-12-20 10:41
> The openssl.cnf file will now be auto-discovered from your system configuration.

This doesn't work for FPM yet, correct?

**Comment by Log1x** [comment] 2023-12-20 22:35
Any ETA on a release for this?

**Comment by dluague** [comment] 2023-12-24 23:30
after hours of debugging it finally works in my end. I just need to copy the content of /Users/[YOUR-USERNAME]/Library/Application Support/Herd/config/valet/CA/LaravelValetCASelfSigned.pem to /Users/[YOUR-USERNAME]/Library/Application Support/Herd/config/php/cacert.pem

**Comment by justindantzer** [comment] 2024-01-05 02:45
> after hours of debugging it finally works in my end. I just need to copy the content of /Users/[YOUR-USERNAME]/Library/Application Support/Herd/config/valet/CA/LaravelValetCASelfSigned.pem to /Users/[YOUR-USERNAME]/Library/Application Support/Herd/config/php/cacert.pem

Just ran into this issue this week. Wasn't sure if it was an OS update, a Hers update, or a Homebrew package update, but this solved the issue for me as well. Thanks for the tip!

**Comment by richardjkeys** [comment] 2024-01-10 14:54
> > The openssl.cnf file will now be auto-discovered from your system configuration.
> 
> This doesn't work for FPM yet, correct?

I don't believe so - just hit a problem using curl to send push notifications; FPM can't seem to load my certificate

**Comment by mpociot** [comment] 2024-01-10 14:55
Hm could you provide an example script where you run into an issue?

**Comment by richardjkeys** [comment] 2024-01-10 15:31
@mpociot Might be my mistake, apologies - seems to work as expected when I use Guzzle instead of vanilla curl. I'll do some more testing.

**Comment by jplhomer** [comment] 2024-03-12 14:08
👋 does anyone have tips for where the OpenSSL config can be edited? I've tried updating my local `/etc/ssl/openssl.cnf` as well as `/opt/homebrew/etc/openssl@3/openssl.cnf`, but neither seem to have an impact on the `php-fpm` being run inside Herd. 

For reference, the options I'm trying to change: https://stackoverflow.com/questions/73832854/php-openssl-pkcs12-read-error0308010cdigital-envelope-routinesunsupported

**Comment by cheesegrits** [comment] 2024-05-04 21:53
@jplhomer did you figure this out?  I have the exact same problem, needing to use a PKCS12 cert for testing against a TAK server.

**Comment by jplhomer** [comment] 2024-05-05 12:16
@cheesegrits no, I ended up disabling Herd and moving back to Valet.

**Comment by elalecs** [comment] 2024-08-23 23:25
This issue should not be closed. @dluague correctly identified the problem: PHP doesn't recognize Valet's self-generated certificates as valid.

When accessing site2 from site1 (e.g., using file_get_contents), PHP fails to validate the certificate, resulting in an error.

Improved workaround:
1. Backup the original cacert.pem:
   cp Herd/config/php/cacert.pem Herd/config/php/original_cacert.pem

2. Create a combined PEM file in the original location:
   cat Herd/config/php/original_cacert.pem Herd/config/valet/CA/LaravelValetCASelfSigned.pem > Herd/config/php/cacert.pem

This solution maintains the original PHP certificates while adding Valet's, allowing secure communication between local sites and external services. No php.ini modifications are required.

Feature request: Implement automatic creation and configuration of this combined certificate file when generating new certificates through the Herd interface.

Alternative workaround: Avoid using self-signed certificates altogether.

**Comment by hadesunseenn** [comment] 2024-09-15 07:02
this issue is still not fixed in version 1.10.0

**Comment by handhikadj** [comment] 2024-11-01 13:07
this is not fixed.
when I do `curl` or `file_get_contents` on my own local site using ngrok domain, there's this error:
<img width="1143" alt="image" src="https://github.com/user-attachments/assets/abe7e1ab-59b8-422f-9999-cf07cbd91b32">
in `phpinfo()` , the `cacert.pem` file doesn't show on `openssl.cafile` property:
<img width="983" alt="image" src="https://github.com/user-attachments/assets/9dcece4e-7f21-4d66-9dba-59cd04d255a1">
but on terminal, it's showing when I run `php -i | grep cacert` command
I believe this is still not fixed on the php-fpm

**Comment by JackWH** [comment] 2024-11-05 20:22
I can confirm @elalecs' improved workaround solved this for me:
 
> 1. Backup the original cacert.pem:
>    cp Herd/config/php/cacert.pem Herd/config/php/original_cacert.pem
> 2. Create a combined PEM file in the original location:
>    cat Herd/config/php/original_cacert.pem Herd/config/valet/CA/LaravelValetCASelfSigned.pem > Herd/config/php/cacert.pem

Thank you! 🙏

**Comment by mityukov** [comment] 2025-02-12 05:18
I'd like to add an observation:

Use php 8.2:
```
> php artisan tinker
> file_get_contents('https://dummyjson.com/todos'); // => all good
```

Use php 8.1:
```
> php artisan tinker
> file_get_contents('https://dummyjson.com/todos');
> // WARNING  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
> // error:0A000086:SSL routines::certificate verify failed.
```

Use php 8.0:
```
> php artisan tinker
> // Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".
> php -a
> var_dump(file_get_contents('https://dummyjson.com/todos')); // all good again


So, something's Off with php **8.1**

**Comment by RichardAnderson** [comment] 2025-07-17 21:34
I too am having this issue on Windows - clean install of Herd, one site cannot access the other, due to `SSL routines::certificate verify failed`.

@mpociot please can this be reopened?  It's impossible to work with Herd when using sites that need to access one another.
