### ISSUE TITLE
[Bug]: Expose Token: preg_match(): Allocation of JIT memory failed

### ISSUE THREAD

**Issue by pryley** [beyondcode/herd-community#136] opened 2023-08-22 21:21 UTC
### Operating system version

macOS Venture 13.4.1 (c)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.2.0 (build 14)

### PHP Version

PHP 7.4.33

### Bug description

<img width="1022" alt="image" src="https://github.com/beyondcode/herd-community/assets/134939/fe37ed90-23e8-4cc5-8e73-e25bb6b21c92">

```
Warning: preg_match(): Allocation of JIT memory failed, PCRE JIT will be disabled. This is likely caused by security restrictions. Either grant PHP permission to allocate executable memory, or set pcre.jit=0 in phar:///Users/me/Library/Application Support/Herd/bin/expose/.box/vendor/composer/semver/src/VersionParser.php on line 48

Box Requirements Checker
========================

> Using PHP 7.4.33
> PHP is using the following php.ini file:
  WARNING: No configuration file (php.ini) used by PHP!

> Checking Box requirements:
  E..

                                                                                
 [ERROR] Your system is not ready to run the application.                       
                                                                                

Fix the following mandatory requirements:
=========================================

 * The application requires the version "^8.1" or greater.
```

### Steps to reproduce

1. Switch PHP version to 7.4
2. Restart Herd
3. Open Settings > Expose

**Comment by jvega** [comment] 2023-08-23 01:59
php 7.4 is not using custom `php.ini`

<img width="900" alt="CleanShot 2023-08-22 at 21 57 57@2x" src="https://github.com/beyondcode/herd-community/assets/926380/f72fc15f-cd87-4868-8e7b-8bbc38add8cc">

**Comment by mpociot** [comment] 2023-08-24 10:16
Please try and create a custom `php.ini` file at ~/Library/Application Support/Herd/config/php` directly. This should then be used with PHP 7.4 - this is a caching related PHP 7.4 issue that will be resolved with a new PHP 7.4 binary update.

**Comment by pryley** [comment] 2023-08-24 16:43
This does not solve the issue. A php.ini file already exists in that location. 

<img width="888" alt="image" src="https://github.com/beyondcode/herd-community/assets/134939/9083c227-8605-46b3-b79f-30f53e79b651">

**Comment by mpociot** [comment] 2023-08-24 18:00
Please copy the php.ini in the "php" directory as well. Not just the version folder.

**Comment by pryley** [comment] 2023-08-24 18:26
1. Copied php.ini into php folder
<img width="489" alt="image" src="https://github.com/beyondcode/herd-community/assets/134939/184dea07-a06c-4ea1-b3af-76fc7d7aa899">

2. Restarted Herd (with PHP 7.4 in use). FYI: it shows FPM-8.1 enabled even though PHP 7.4 is in use (kinda confusing, but there it is)
<img width="236" alt="image" src="https://github.com/beyondcode/herd-community/assets/134939/25054408-f8c2-4e08-b4ce-c226073d3e4b">

4. Expose Token error
<img width="1022" alt="image" src="https://github.com/beyondcode/herd-community/assets/134939/7d72aa13-fbbd-4c1b-a303-f7b064793b44">

**Comment by biplobice** [comment] 2023-12-15 01:35
I'm facing the same problem and the suggested solution doesn't work!

**Comment by EdisonLopezEC** [comment] 2024-01-25 21:04
I can't solve this problem

**Comment by DennisHalili** [comment] 2024-01-26 09:10
I can't solve this problem either, last week, Last week, it worked well when I switched to 7.4 but after upgrading, I received this error.

**Closed** 2024-02-12 11:16 UTC

**Comment by tembra** [comment] 2024-02-19 23:32
@mpociot 

> PHP 7.4 looks for php.ini files in the following locations:
> 
> ```
> ~/Library/Application Support/Herd/config/php
> ~/Library/Application Support/Herd/config/php/74
> ```

My Herd 1.4.1 is looking nowhere for PHP 7.4:
```bash
php74 --ini
Configuration File (php.ini) Path: /lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)
```

However for PHP 8.2 it's looking in right path:
```bash
php82 --ini
Configuration File (php.ini) Path: /lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: /Users/TDT/Library/Application Support/Herd/config/php/82/
Additional .ini files parsed:      /Users/TDT/Library/Application Support/Herd/config/php/82/php.ini
```

I just installed PHP 7.4 to run an old Laravel project and after run `php artisan` I got the error:
```bash
Warning: preg_match(): Allocation of JIT memory failed, PCRE JIT will be disabled. This is likely caused by security restrictions. Either grant PHP permission to allocate executable memory, or set pcre.jit=0 in ...../vendor/vlucas/phpdotenv/src/Parser.php on line 121
```

So I changed the php.ini of PHP 7.4 on Herd's folder but it's not reading the configuration from there.

**Comment by tembra** [comment] 2024-02-20 00:17
The php74-fpm seems to look on right path. Below is the `phpinfo()` result:

<img width="970" alt="image" src="https://github.com/beyondcode/herd-community/assets/6340360/719c04c8-c670-4a13-b92c-ba0d57578bcb">

**Comment by Ross-C** [comment] 2024-05-09 06:33
I am having this same issue followed all steps as above and can see ini file is loaded but still get the error

```
Configuration File (php.ini) Path: /lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: /Users/ross/Library/Application Support/Herd/config/php/74/
Additional .ini files parsed:      /Users/ross/Library/Application Support/Herd/config/php/74/php.ini
```

`Warning: preg_match(): Allocation of JIT memory failed, PCRE JIT will be disabled. This is likely caused by security restrictions. Either grant PHP permission to allocate executable memory, or set pcre.jit=0 in /Users/ross/Projects/Web/Laravel/[MyProject]/vendor/laravel/framework/src/Illuminate/Support/Env.php on line 93`

PHP 7.4
Sonoma 14.4.1
Macbook Air M1

I coudn't find a working solution in this bug ot the linked duplicate

**Comment by sschlein** [comment] 2024-05-09 06:44
Expose doesn't work with PHP 7.4. We have an open issue internally to automatically use a working version if it's installed but that's not implemented yet. 

Please switch to 8.1 or newer as your main version when using Expose and isolate your site with 7.4 🙂

**Comment by Ross-C** [comment] 2024-05-09 06:46
Sorry I have posted this on the wrong bug then, I am getting this message in my browser when running a Laravel 8 app with php artisan serve

**Comment by sschlein** [comment] 2024-05-09 06:52
Does that also happen if you run your app via its domain, so https://your-app-folder-name.test ?

While `php artisan serve` is generally supported, I wonder why people use it when their sites are also accessible via a proper web server (nginx)

**Comment by Ross-C** [comment] 2024-05-09 07:04
It doesn't happen if i run like this, that's fine I'm new to Herd.  this is a better to way to do it anyway thanks 🤩

**Comment by biplobice** [comment] 2024-06-05 06:26
### Note
**Using PHP 8.2 resolves the issue.**
If you need to make any customizations, please do so using PHP 8. If you need to run the application with PHP 7, you can switch to PHP 7 after setting it up with PHP 8. It will run normally.

**Comment by jverkoey** [comment] 2024-09-23 17:37
Reviving this thread as it seems to have resurfaced with macOS 15.1 Beta (24B5035e).

```
PHP 8.3.11 (cli) (built: Aug 27 2024 19:16:34) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.11, Copyright (c), by Zend Technologies
```

```
[Mon Sep 23 10:35:32.020878 2024] [php:warn] [pid 54430] [client ::1:54818] PHP Warning:  preg_match(): Allocation of JIT memory failed, PCRE JIT will be disabled. This is likely caused by security restrictions. Either grant PHP permission to allocate executable memory, or set pcre.jit=0 in /Users/fearlessdesign/Sites/phpmyadmin/vendor/slim/psr7/src/Factory/UriFactory.php on line 82
```

**Comment by jverkoey** [comment] 2024-09-23 17:39
https://www.codingforum.net/forum/server-side-development/apache-configuration/2435189-ah00052-child-pid-n-exit-signal-segmentation-fault-11 might be relevant.
