### ISSUE TITLE
[Bug]: Tinker opens if try to restore a tab in Chome on Windows

### ISSUE THREAD

**Issue by elnurxf** [beyondcode/herd-community#590] opened 2024-04-02 12:26 UTC
### Platform

Windows

### Operating system version

Windows 11 Pro x64 (23H2)

### System architecture

Windows

### Herd Version

1.0.1

### Bug description

On regular Google Chrome window when you try to re-open closed tab - Tinkerwell opens a terminal window.
Since It's an ElectronJS app, probably it is catches a hotkey defined in Herd.

Reseting this hotkey helps, but I would recommend to avoid use of well-known and most used hotkeys, IMHO.

### Steps to reproduce

Press: CTRL+SHIFT+T

**Comment by mechelon** [comment] 2024-04-02 12:26
Duplicate of #583

**Closed by mechelon** 2024-04-02 12:26 UTC
Labels: windows
