### ISSUE TITLE
[Bug]: Herd asks for email / license key on every system reboot

### ISSUE THREAD

**Issue by tvarwig** [beyondcode/herd-community#842] opened 2024-06-25 22:16 UTC
### Platform

macOS

### Operating system version

MacOS Sonoma 14.5

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.7.1 (Build: 28)

### PHP Version

PHP 8.3.8

### Bug description

Every time I restart my Mac Herd is set to start on system startup. The program asks for my email / license key every time. 

### Steps to reproduce

Restart Mac, Have Herd auto start

**Comment by mpociot** [comment] 2024-06-25 22:21
This is a duplicate of #832

See this comment for the fix: https://github.com/beyondcode/herd-community/issues/832#issuecomment-2185261756

**Closed** 2024-06-25 22:21 UTC
Labels: macOS
