### ISSUE TITLE
[Bug]: Can't run php artisan serve

### ISSUE THREAD

**Issue by RehamTammam1** [beyondcode/herd-community#810] opened 2024-06-17 00:42 UTC
### Platform

Windows

### Operating system version

Windows 10

### System architecture

Windows

### Herd Version

1.0.7

### Bug description

I'm trying to run php artisan serve and each time I get the following, any help
![image](https://github.com/beyondcode/herd-community/assets/163147758/fcbb6b05-478d-4b37-bfae-7c09ac066a7c)

**Comment by mpociot** [comment] 2024-06-17 08:28
This is a duplicate of https://github.com/beyondcode/herd-community/issues/737

But you should just access your site via roroecommerce.test instead of using artisan serve :)

**Closed by mpociot** 2024-06-17 08:28 UTC
Labels: windows
