### ISSUE TITLE
[Bug]: Link existing project gives error The Herd Desktop application is not running. Please start Herd and try again. Command "link" is not defined.

### ISSUE THREAD

**Issue by KjartanBourgeois** [beyondcode/herd-community#919] opened 2024-08-06 14:37 UTC
### Platform

Windows

### Operating system version

Windows 11 22H2

### System architecture

Windows

### Herd Version

1.9.0

### PHP Version

PHP 8.3

### Bug description

When I want to link an existing project I get this error: "The Herd Desktop application is not running. Please start Herd and try again. Command "link" is not defined."
Creating an new project works. 

### Steps to reproduce

- Fresh install
- Link existing project

### Relevant log output

```shell
[2024-08-06 16:23:27.254] [error] Error occurred in handler for 'valet.getDriver': Error: Command failed: "%USERPROFILE%\.config\herd\bin\php83\php.exe" "%USERPROFILE%\.config\herd\bin\herd.phar" which
                        
  Command "which" is not defined.  
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
```

**Comment by sschlein** [comment] 2024-08-14 13:10
The problem is likely related to a used port (9001) on your machine and Herd can't start its internal API server that we use for communication between the CLI and the app. Herd Pro users can change this port in the Dump settings but if you are using the free version, there is no way to do that from the GUI at the moment.

Please quit Herd and go to your configuration files at `%USERPROFILE%\.config\herd\config`. There is a `config.json` that has an `apiPort` in it. If you change that from 9001 to something else like 9457 and start Herd, it should start working.


I also changed the settings for this and moved it to the General tab. This will be released within the next 2-3 weeks :)

**Closed** 2024-08-20 08:55 UTC
Labels: fixed-in-next-release, windows
