### ISSUE TITLE
[Bug]: Mail Service Fails to Start on System Boot

### ISSUE THREAD

**Issue by SHSharkar** [beyondcode/herd-community#1021] opened 2024-09-20 15:11 UTC
### Platform

macOS

### Operating system version

macOS Sequoia 15.0 (24A335)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

Herd 1.11.0 (Build: 33)

### PHP Version

PHP 8.3.11 (cli) (built: Sep 10 2024 15:12:42) (NTS)

### Bug description

The Herd mail service fails to start properly during system boot, but works fine when manually restarting Herd services.

### Steps to reproduce

1. Boot the operating system
2. Observe that the mail service fails to start

### Relevant log output

```shell
Port 2525 is free. Starting mailserver.
Mailserver listening on port 2525
node:events:515
      throw er; // Unhandled 'error' event
      ^

Error: WebSocket was closed before the connection was established
    at WebSocket.close (/snapshot/herd-mailserver/node_modules/ws/lib/websocket.js:292:7)
    at ReconnectingWebSocket._disconnect (/snapshot/herd-mailserver/node_modules/reconnecting/dist/reconnecting-websocket-cjs.js:541:22)
    at ReconnectingWebSocket._handleError (/snapshot/herd-mailserver/node_modules/reconnecting/dist/reconnecting-websocket-cjs.js:180:19)
    at ReconnectingWebSocket._handleTimeout (/snapshot/herd-mailserver/node_modules/reconnecting/dist/reconnecting-websocket-cjs.js:531:14)
    at Timeout.<anonymous> (/snapshot/herd-mailserver/node_modules/reconnecting/dist/reconnecting-websocket-cjs.js:526:75)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/snapshot/herd-mailserver/node_modules/ws/lib/websocket.js:1033:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.5.0
```

**Comment by mechelon** [comment] 2024-09-23 06:35
Duplicate of #969

**Closed by mechelon** 2024-09-23 06:35 UTC
Labels: macOS
