### ISSUE TITLE
[Bug]: Dumps not showing on Windows

### ISSUE THREAD

**Issue by jrd-lewis** [beyondcode/herd-community#517] opened 2024-03-26 19:22 UTC
### Operating system version

Windows 11

### System architecture

Intel (x86)

### Herd Version

1.0.0

### Bug description

I pressed the antenna icon in the top of the Dumps window, and it didn't display my `dump()` call in either my browser or the Dumps winow.

### Steps to reproduce

- Add a call to `dump()` or `dd()` as part of a route.

Example:
```
public function index(): View
    {
        $posts = Post::latest()->get();
        dump($posts);

        return view('blog.index', compact('posts'));
    }
```

- Turn on the dump interception by pressing the antenna icon.

- Visit the route in the browser.

**Comment by jrd-lewis** [comment] 2024-03-26 19:41
I had no change when I restarted from the GUI and tried again.

Though when I tried in PowerShell with `herd restart`, I did get `PHP Fatal error:  Uncaught TypeError: Valet\Herd::getBasePhpPort(): Return value must be of type int, string returned`

**Comment by mpociot** [comment] 2024-03-26 19:50
Is the Dump server running? You can see it in the Herd Dump settings. 
Maybe the port is taken?
Does it make a difference if you just dump a simple string?

**Comment by jrd-lewis** [comment] 2024-03-26 19:53
It looks to be running from `netstat -a -n | find "9001"`:
```

**Comment by rubendn** [comment] 2024-03-27 04:31
I'm having the same issue with Dumps on Windows 11.

When I click the antenna to turn off dumps, they do show on the page but with dumps turned on, they don't show on the page nor in Dumps.

This is what it shows when I run netstat:


```
 TCP    0.0.0.0:9001           0.0.0.0:0              LISTENING

 TCP    127.0.0.1:57437        127.0.0.1:9001         TIME_WAIT

 TCP    [::]:9001              [::]:0                 LISTENING
```

I also turned off Windows Firewall completely to test but that had no effect.

**Comment by mpociot** [comment] 2024-03-27 10:52
Can you share a screenshot of the Dashboard? Are all services marked as running/green?

**Comment by rubendn** [comment] 2024-03-27 12:19
Here is the screnshot:

![Herd](https://github.com/beyondcode/herd-community/assets/8990606/f85ea1bf-0e5c-43c7-b976-77cd289119d5)

**Comment by rubendn** [comment] 2024-03-27 12:45
Update:

Works:
```
dump('This is the dump.');
```
Does Not Work:
```
dump($this->items);
```

**Comment by mpociot** [comment] 2024-03-27 12:46
Okay, that's good to know. I'll check if there's an issue with the payload size and fix it in the next release.

**Comment by jrd-lewis** [comment] 2024-03-27 12:52
> Update:
> 
> Works:
> 
> ```
> dump('This is the dump.');
> ```
> 
> Does Not Work:
> 
> ```
> dump($this->items);
> ```

Interesting. I can't even get the "this is the dump" message to show up. It is intercepting it since it isn't in the browser; but it's not in the Dumps window.

@mpociot And this is my Dashboard screenshot:

![image](https://github.com/beyondcode/herd-community/assets/17649602/2872a2a7-d183-4f9d-b718-3cc023606ffa)

**Comment by rubendn** [comment] 2024-03-27 12:59
Note:

I changed the collection size from 20 to 1 and it works with both dump($this->items) and dd($this->items).  dd does stop execution of the page (Not sure if that is the intended behavior).

**Comment by IvanKovachev** [comment] 2024-03-27 13:46
I have the same issue  - all services are in green, and Dumps are not shown in the viewer. They seem to be captured, though, because they are not visible in the browser when intercepting is on.

Doesn't work even with trying to dump a single character string.

**Comment by mpociot** [comment] 2024-03-27 14:12
I assume all these issues are related to the payload size

**Comment by jrd-lewis** [comment] 2024-03-27 14:36
> I assume all these issues are related to the payload size

I haven't touched any of the default settings aside from installing PHP 8.2 as a secondary version. So, I don't know what it'd be related to.

**Comment by mpociot** [comment] 2024-03-27 14:57
Yeah, it's something we need to fix on our side 👍

**Comment by mpociot** [comment] 2024-03-28 13:14
Fixed in version 1.0.1 
https://herd.laravel.com/changelog/windows#101

**Closed by mpociot** 2024-03-28 13:14 UTC
Labels: fixed-in-next-release, windows

**Comment by jrd-lewis** [comment] 2024-03-28 13:41
I just tested with 1.0.1 and it's still not showing up.

**Comment by mpociot** [comment] 2024-03-28 13:46
@jrd-lewis then it's not related to the payload size for you (like it was for others in this thread)
Can you create a new issue so we can follow up there and identify what's going on?
