### ISSUE TITLE
[Bug]: Minor path issues

### ISSUE THREAD

**Issue by MrBMT** [beyondcode/herd-community#639] opened 2024-04-12 14:04 UTC
### Platform

macOS

### Operating system version

macOS Sonoma 14.4.1 (23E224)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.5.0 (Build: 23)

### PHP Version

PHP 8.1.26 (cli) (built: Dec 21 2023 08:51:01) (NTS)

### Bug description

When installing Herd, I've noticed that there are extra `/` being added to a few places where they are not needed.

e.g. in .zshrc:
`export PATH="/Users/owner/Library/Application Support/Herd/bin/":$PATH`
There should not be a trailing slash after `bin`, it should be:
`export PATH="/Users/owner/Library/Application Support/Herd/bin":$PATH`

If you check your Herd bin directory (e.g.) `/Users/owner/Library/Application Support/Herd/bin/`
You'll find that `php` is sysmlinked to the directory with a double slash too, e.g. `/Users/owner/Library/Application Support/Herd/bin//php81` instead of `/Users/owner/Library/Application Support/Herd/bin/php81`

### Steps to reproduce

Install Herd
In this case, then switch to using PHP 8.1, however the issue is the same no matter which you use

**Comment by mpociot** [comment] 2024-05-13 09:06
Duplicate of #187

**Closed by mpociot** 2024-05-13 09:06 UTC
Labels: macOS
