### ISSUE TITLE
[Bug]: Whenever restart the herd it will display this kind of message!

### ISSUE THREAD

**Issue by utsavsomaiya** [beyondcode/herd-community#698] opened 2024-04-28 06:28 UTC
### Platform

macOS

### Operating system version

Sonoma 14.4.1 (23E224)

### System architecture

Intel (x86)

### Herd Version

1.0.6

### PHP Version

PHP 8.2

### Bug description

<img width="1062" alt="image" src="https://github.com/beyondcode/herd-community/assets/96036522/0c2129af-288d-48ea-b5aa-df26a49aa294">

**Comment by mpociot** [comment] 2024-04-28 10:23
Duplicate of https://github.com/beyondcode/herd-community/issues/136

**Closed by mpociot** 2024-04-28 10:23 UTC
Labels: macOS
