### ISSUE TITLE
[Bug]: Sites Not Displayed After Switching to PHP Version 7.4.33

### ISSUE THREAD

**Issue by dcygan** [beyondcode/herd-community#326] opened 2024-02-06 18:59 UTC
### Operating system version

macOS Sonoma 14.2.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.0 (Build: 20)

### PHP Version

PHP 7.4.33

### Bug description

After switching to PHP version 7.4.33 in the latest version of the Herd application on Mocos, no sites are displayed in the dashboard or sites section. This issue does not occur when using other PHP versions such as 8.0 and 8.2.

<img width="978" alt="obraz" src="https://github.com/beyondcode/herd-community/assets/13206744/9f763964-c910-4cbd-b278-11e47fceed76">

<img width="978" alt="obraz" src="https://github.com/beyondcode/herd-community/assets/13206744/32fc233d-83f6-4d51-9140-add65b301ee3">

For PHP version 7.4:
<img width="978" alt="obraz" src="https://github.com/beyondcode/herd-community/assets/13206744/4556f2a4-8f57-46fd-a458-32459704e2ac">

After switching to PHP version 8.2:
<img width="1022" alt="obraz" src="https://github.com/beyondcode/herd-community/assets/13206744/f914ecd9-8a1a-433a-a2e0-7b8688dc553e">

**Comment by dcygan** [comment] 2024-02-06 19:26
<img width="1136" alt="obraz" src="https://github.com/beyondcode/herd-community/assets/13206744/1ffdd82c-0a1f-4940-a929-389169227901">

**Comment by MrDigex** [comment] 2024-02-06 20:17
I had a similar issue where I couldn't view some websites. It seems that your system is using a different PHP version than the one used by Herd. I noticed that in your screenshot, your PHP version was 7.4, while Herd was running on version 8.3. I resolved this issue by following these steps:

1. First, I ran the command `brew unlink php`.
2. Then, I ran `brew link --overwrite php@8.3`. or the PHP version that you want
3. Next, I selected the same version in Herd.
4. Finally, I restarted Herd and was able to see the sites displayed properly. 

Hope this helps!

**Comment by dcygan** [comment] 2024-02-07 09:58
Indeed, after installing the new version, Herd in my system uses PHP 8.3, which I did not have installed. I installed PHP 8.3 using Herd, and now everything works correctly. I'm only wondering about the fact that when selecting a version other than 7.4, Herd uses the chosen one, but after selecting 7.4, Herd uses 8.3.

**Comment by sschlein** [comment] 2024-02-07 11:47
`which php` points to the Herd binary of 8.3 when you select 7.4?

**Comment by dcygan** [comment] 2024-02-07 11:54
<img width="1092" alt="obraz" src="https://github.com/beyondcode/herd-community/assets/13206744/de1b9f41-9b2b-46b2-baa8-5f5dce739cbd">

**Comment by iruzevic** [comment] 2024-02-08 08:21
I managed to fix this by installing the php8.3 as I didn't have the php8.3 bin after the restart of the app and it started to work.

Make sure you have the latest PHP version bin installed

**Comment by iobrado** [comment] 2024-02-08 10:05
In my case, installing PHP 8.3 did help temporarily, but at one point I started having problems on PHP 7.4 again.

The workaround I use to fix it is opening the `Dumps` window, and activating/deactivating intercepting dumps (antenna icon). After doing that, PHP 7.4 works properly again for some time and the sites are also displaying in the list.

**Comment by sschlein** [comment] 2024-02-08 13:22
> I have the same issue in version 1.4.0 But I already have all of php versions installed, how can I solve this I need a solution please!!
> 
> I'm so disappointed that once you made it Pro, the essential functionalities are simply not taken care of! 😞

Which shell do you use? If you're using the fish shell, this would be the issue at the moment and it's not 7.4 related.

Do the sites show up in the browser?

**Comment by mkwsra** [comment] 2024-02-08 13:37
Yes, I use Fish

> Do the sites show up in the browser?

Yes they do, but strangely not all of them, so I created an issue #342. some of them (majority) are not opening `502 Bad Gateway`

**Comment by sschlein** [comment] 2024-02-08 13:42
The problem is either a missing or broken herd.json file in your config directory that you can open via "Show php.ini" menu item when clicking on the Herd icon.

We've fixed that for the upcoming version but until this is live, you can fix that by creating a herd.json file with an empty json object in it `{}` and restarting Herd.

The file needs to be placed at: `/Users/YOUR_USER/Library/Application Support/Herd/config`

I am closing this issue because we've resolved it and it'll be fixed very soon.

**Closed by sschlein** 2024-02-08 13:42 UTC
