### ISSUE TITLE
[Bug]: Intrusive Installer

### ISSUE THREAD

**Issue by Kalo79** [beyondcode/herd-community#955] opened 2024-09-02 17:57 UTC
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.10.0

### Bug description

This is more of a feedback and frustration report, than a bug report.
First, as a developer I would like to have control of where the application is installed. A decent installer will always ask you where you want the application to be installed. Herd installer just ran without any prompts.
Second, after the installation was complete, again WITHOUT ANY PROMPTS it attempted to restart my computer and closed my browser and a few other opened apps before I was able to manually interrupt it. :(
Such behavior is unacceptable and more characteristic of a malicious software.
Not a good start for me!

### Steps to reproduce

Run the installer.

**Comment by sschlein** [comment] 2024-09-02 18:11
Herd relies on specific paths to make everything work so choosing the location is not an option for the app. 

I get your frustration about the restart and would like to know more about your setup - because Herd does not require a restart. I've installed the app hundreds of times during testing, on VMs, dedicated machines and multiple versions of Win 10 and 11 and never had a restart. But you're not the first one mentioning that and so I wonder what your system does differently to mine.

**Comment by Kalo79** [comment] 2024-09-02 19:53
If the restart was not initiated by the app, maybe some of the additional software that was installed triggered it.
An additional installation window for "Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.40.33810" popped up during  the installation process. Also a shell window popped up installing Node and something else, but I wasn't paying enough attention at that time.

My Windows specs are:
Edition	Windows 11 Pro
Version	23H2
Installed on	‎25.‎9.‎2022 ‎г.
OS build	22631.4037
Experience	Windows Feature Experience Pack 1000.22700.1027.0

**Comment by Kalo79** [comment] 2024-09-02 20:00
I just tried to uninstall the Visual C++ Redistributable package and got "No action was taken as a system reboot is required" error message. Probably because I interrupted the restart process during the installation. So now I'm pretty sure this is what's causing the issue.

**Comment by sschlein** [comment] 2024-09-02 20:18
Installing this shouldn't require a restart either. 

I haven't tried interrupting the install and maybe breaking something on the way that could lead to such an issue. 

I'd love to hear more from others but this is definitely not the normal or intended behavior.

**Comment by Kalo79** [comment] 2024-09-02 20:22
I want to clarify that I did not interrupt the install process. I interrupted the restart that was initiated after the installation process was complete. And I'm now sure the restart was initiated by the Visual C++ package.

**Comment by MarJose123** [comment] 2024-09-03 08:25
We got the same experience #942.

**Comment by sschlein** [comment] 2024-09-03 08:29
We've already applied a small change that explicitly tells the VC code redistributable to _not_ do a restart. Previous versions didn't need that flag and even today it only seems to happen on some systems so it did not get caught during testing.

**Comment by Kalo79** [comment] 2024-09-03 08:47
Today (after the computer was restarted) I uninstalled everything including the C++ package and ran the same Herd installer I downloaded yesterday and the process went through the C++ package installation again, but this time everything completed normally and no restart was required. Then I removed the C++ package again and Herd seams to be working fine without it. My guess is it updates some system files the first time it is installed and that's why it requires a restart.

**Comment by Kalo79** [comment] 2024-09-03 08:49
Also, uninstalling the C++ package did not produce the "No action was taken as a system reboot is required" this time.

**Comment by Kalo79** [comment] 2024-09-03 08:54
Here is some additional information I found about it that may be of interest to you (@sschlein ):
https://stackoverflow.com/questions/62001965/when-does-visual-c-2015-2019-redistributable-lead-to-pc-reboot
https://stackoverflow.com/questions/76240900/vc-redist-install-passively-without-restart-always-restarting

**Comment by sschlein** [comment] 2024-09-03 09:04
Thanks for that, the 2nd link seems to do the trick and we'll look into that.

**Comment by mpociot** [comment] 2024-09-19 13:13
This is now fixed in Herd 1.11.0

**Closed by mpociot** 2024-09-19 13:13 UTC
Labels: fixed-in-next-release, windows
