### ISSUE TITLE
[Bug]: Snapped Dump Window does not stay in position

### ISSUE THREAD

**Issue by mathiaswillburger** [beyondcode/herd-community#914] opened 2024-08-01 18:09 UTC
### Platform

Windows

### Operating system version

WIndows 11

### System architecture

Intel (x86)

### Herd Version

1.9.0

### Bug description

When snapping the Dump Window to a specific position (e.g., the left side of the screen) and snapping another window to the opposite side (e.g., the right side), the Dump Window reverts to its original position when it is brought back into focus. This requires reorganizing the windows after each dump operation.

**Expected Behavior:**
The Dump Window should remain snapped to the left side of the screen and maintain its position regardless of focus changes or dump operations.

### Steps to reproduce

1. Snap the dump window to the left
2. Snap VSCode to the right
3. Open the browser in another window (not snapped) or on a new desktop
4. Perform an action which triggers a dump
5. The dump window "unsnaps" and places itself in the old position before it was snapped

**Comment by mechelon** [comment] 2024-08-05 13:37
I'm afraid I'm not able to reproduce this - Can you share your exact Windows version?

**Comment by mathiaswillburger** [comment] 2024-08-06 00:33
I am using Windows 11 Pro, 10.0.22.631 Build 22631

I can offer two more variations how to reproduce the issue:

1. Place the Herd Dump window in the middle of the screen
2. Grab it with the icon and snap it to the left side of the Windows desktop
3. Snap an existing browser window to the right
4. Switch the desktop to another screen where VsCode is open (but it should have the same effect on the same desktop too)
5. Variants 
a. Variant A: open tinker in a Laravel Console and run `dump("dump")` (do not use Tinkerwell)
b. Variant B: create a custom route in the application and call the route in the browser on the other desktop, e.g. 
```
    Route::get('dump', function () {
        dump('dump');
    });  
```
6. The dump icon in the taskbar starts blinking, indicating something happened. When switching back to the desktop where the Dump window is located, it is again positioned in the middle of the screen, not snapped to the left.

**Comment by mechelon** [comment] 2024-08-13 11:20
This seems to be a bug in Electron: https://github.com/electron/electron/issues/25359

I'll close this as we have to wait for Electron to fix this bug. As soon as that happens, we'll have this fixed in Herd as well.

**Closed by mechelon** 2024-08-13 11:20 UTC
Labels: windows
