### ISSUE TITLE
[Bug]: OpenSSL – unsafe legacy renegotiation disabled

### ISSUE THREAD

**Issue by mikerockett** [beyondcode/herd-community#115] opened 2023-08-11 06:08 UTC
### Operating system version

macOS Ventura 13.4 (22F66)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.2

### PHP Version

PHP 8.2.8 (cli) (built: Jul 28 2023 13:55:05) (NTS)

### Bug description

When trying to interact with a URL via Guzzle, fopen, file_get_contents, and the like, I'm getting the following error:

> cURL error 35: OpenSSL/3.1.1: error:0A000152:SSL routines::unsafe legacy renegotiation disabled (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://some_url

I did some looking around, and people say that one can change OpenSSL to use legacy connections, but I'd like to avoid that.

I did, however, try adding this to my OpenSSL config, but it didn't take effect – a good sign that something else is wrong, perhaps?

```ini
[system_default_sect]
Options = UnsafeLegacyServerConnect
```

### Steps to reproduce

As above (just use a function that interacts with OpenSSL).

**Comment by mpociot** [comment] 2023-08-11 06:23
Does it matter which URL you're trying to access?

**Comment by mikerockett** [comment] 2023-08-11 08:12
Ah, didn't even think to check 🙈 

Appears to only be with that URL, so my assumption then is that the remote is the problem…? Used to work, but I guess that a specific OpenSSL version is preventing it.

**Comment by mpociot** [comment] 2023-08-14 06:48
Weird - let me know if you're able to reproduce it.
I'll close this though, as it seems to be somehow application specific, and not an issue with Herd in general.

**Closed by mpociot** 2023-08-14 06:48 UTC

**Comment by austingrove** [comment] 2023-09-22 00:06
I receive the same error when attempting to get "https://ordspub.epa.gov/ords/pesticides/apprilapi/?q=" but I don't encounter the error when requesting other websites (reddit.com). 

I've tried withOutVerifying(), timeout(60), and setting curl version back to CURL_SSLVERSION_TLSv1_2 without avail.

**Comment by georgeboot** [comment] 2024-01-31 15:42
@mpociot this is indeed an issue. I believe due to some servers supporting >= TLS 1.2 but not supporting [safe renegotiation](https://blog.qualys.com/product-tech/2010/10/06/disabling-ssl-renegotiation-is-a-crutch-not-a-fix-2).

The server admins should fix it, but some control over the curl settings used would be ideal.
