### ISSUE TITLE
[Bug]: uninstall herd

### ISSUE THREAD

**Issue by nick322** [beyondcode/herd-community#11] opened 2023-07-21 10:15 UTC
### Operating system version

macOS Ventura 13.3

### Herd Version

1.0.6

### PHP Version

PHP 7.4.33 (cli) (built: Jun 17 2023 06:48:54) ( NTS )

### Bug description

When Uninstalling Herd after 
my php config exist Herd config
```
❯ php --ini
Configuration File (php.ini) Path: /usr/local/etc/php/7.4
Loaded Configuration File:         /usr/local/etc/php/7.4/php.ini
Scan for additional .ini files in: /Users/nick/Library/Application Support/Herd/config/php/:/Users/nick/Library/Application Support/Herd/config/php/:
Additional .ini files parsed:      /usr/local/etc/php/7.4/conf.d/error_log.ini,
/usr/local/etc/php/7.4/conf.d/ext-opcache.ini,
/usr/local/etc/php/7.4/conf.d/php-memory-limits.ini
```

I found out that my .zshrc file still has
```
# Herd injected PHP binary.
export PATH="/Users/nick/Library/Application Support/Herd/bin/":$PATH
export PHP_INI_SCAN_DIR="/Users/nick/Library/Application Support/Herd/config/php/":$PHP_INI_SCAN_DIR
```

**Comment by deleugpn** [comment] 2023-07-21 21:55
Duplicate of #2

**Closed** 2023-07-22 18:02 UTC
