### ISSUE TITLE
[Bug]: 502 Bad Gateway errors on any POST submit (same Laravel Valet bug #1433)

### ISSUE THREAD

**Issue by neurotools** [beyondcode/herd-community#76] opened 2023-07-31 16:17 UTC
### Operating system version

macOS Ventura 13.4.1 (c)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.1 (Build 12)

### PHP Version

PHP 8.2.8 (cli) (built: Jul 28 2023 13:55:05) (NTS)

### Bug description

Apparently Herd is also affected by the same bug that is affecting Laravel Valet on MacOS (M1).

https://github.com/laravel/valet/issues/1433

I'm getting **502 Bad Gateway** errors when doing any "POST" request to my local application. 

### Steps to reproduce

Create a new Laravel Application.

Create a form with POST method o a controller method (with or without a FormRequest).

Submit the form...

502 Bad Gateway

### Relevant log output

```shell
2023/07/31 12:08:24 [error] 20323#4392398: *479 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: site.test, request: "POST /form HTTP/2.0", upstream: "fastcgi://unix:/Users/user/Library/Application Support/Herd/herd.sock:", host: "site.test", referrer: "https://site.test/form"
```

**Comment by mpociot** [comment] 2023-07-31 18:59
@neurotools should I be able to reproduce this all the time?
It still works for me (please note that I just updated to macOS 13.5)

**Comment by mpociot** [comment] 2023-08-08 21:12
Closing this as I'm unable to reproduce it. Feel free to reopen this if it still exists for you

**Closed by mpociot** 2023-08-08 21:12 UTC

**Comment by ebergsma** [comment] 2023-10-25 09:13
I am getting this same problem. For me, it lies in the form having an email field and the validation rule: 
`'email' => ['required', 'string', 'email:rfc,dns', 'max:255'],`

Removing the `'email:rfc,dns'` makes the form work as intended.

For now im substituting with a regex, but i hope it gets fixed.

**Comment by RemiHin** [comment] 2023-12-11 14:10
I'm still having this issue. @ebergsma situation is what works for me. Seems to break on using that rule.

**Comment by neurotools** [comment] 2024-01-04 19:31
I can confirm the same issue. The 'email:dns' rule on the FormRequest validation triggers the "502 Bad Gateway" error. Removing the "dns" rule fixes the problem. Same issue happened with Valet.

**Comment by AndrewGotham** [comment] 2024-08-03 05:40
I have to confirm this problem too.
Hopefully it will help shrink down what the problem is.

macOS Sonoma 14.5 (23F79)
Herd - fresh new installation 1.9.1

Sites - both taken from other folders and created inside Herd via built-in procedure - lead to 502 error Bard Gateway

Php version seems to be causing the problem.

Adding php 8.3 to fresh installation (and nothing else) leads to 502 error.

Adding php 8.2 to the bundle (not touching anything else) resolves everything, sites opens as needed with both php 8.3 and 8.2.
