### ISSUE TITLE
[Bug]: Dump window tabs not working

### ISSUE THREAD

**Issue by jjcsinke** [beyondcode/herd-community#1014] opened 2024-09-20 07:37 UTC
### Platform

macOS

### Operating system version

macOS 15.0

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.0 build 33

### PHP Version

N/A

### Bug description

In the dump window I can't use the tabs to switch to, for example, the queries list. 

### Steps to reproduce

Open dump window,
Do some stuff in a laravel local site,
Try switching to a tab with some entries in it,
Doesn't work.

See attached screen recording.
https://github.com/user-attachments/assets/ce533913-0da9-40c2-9b54-a0d793aa7bd6

**Comment by sschlein** [comment] 2024-09-20 08:00
This seems to be a macOS 15 Sequoia issue that we need to debug, I can reproduce it on my machine.

**Comment by mpociot** [comment] 2024-09-25 12:15
This will be fixed in the next release 🎉

**Comment by mpociot** [comment] 2024-10-01 10:22
This is now fixed in Herd 1.11.1

**Closed by mpociot** 2024-10-01 10:22 UTC
Labels: fixed-in-next-release, macOS, macOS Sequoia support
