### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by brain82** [beyondcode/herd-community#96] opened 2023-08-04 12:01 UTC
### Operating system version

macOS Ventura 13.4.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.1.1

### PHP Version

8.1.22

### Bug description

**Error**: All Inertia requests must receive a valid Inertia response, however a plain JSON response was received.

I get the above error when clicking links in my inertia app. This has works perfectly when using laravel valet.

**Comment by brain82** [comment] 2023-08-04 12:33
@mpociot  Thanks for the quick response but I'm not sure what you're asking for.

**Comment by brain82** [comment] 2023-08-04 12:44
I don't know if this helps @mpociot 

**Valet**
<img width="566" alt="response-header-valet" src="https://github.com/beyondcode/herd-community/assets/6013683/e17c65ff-3ca3-46dc-96ef-d2586e4227c7">

**Herd**
<img width="468" alt="reponse-header-herd" src="https://github.com/beyondcode/herd-community/assets/6013683/33276b76-03dd-4bff-8a12-4130f4fa9126">

**Comment by mpociot** [comment] 2023-08-04 12:56
And what's the actual response?

**Comment by brain82** [comment] 2023-08-04 13:10
The response is json

<img width="949" alt="image" src="https://github.com/beyondcode/herd-community/assets/6013683/ae5c1011-bdc7-4ebf-ab74-2238b45ea3b0">

**Comment by brain82** [comment] 2023-08-04 18:52
@mpociot If seems fine with a fresh install.

All I can think of is that it may be because of the version of the packages the application is on (shown below).

Laravel framework - 9.37
Laravel Jetstream - 2.12.4
Inertia Laravel - 0.6.3

Inertia - 0.10.1
Inertia Vue - 0.7.2

**Comment by mpociot** [comment] 2023-08-17 09:20
Hm I'm also unable to reproduce it with these specific versions. If you can provide something reproducable (like a demo repository) feel free to re-open this one.
As it works with the latest versions of the package, I'm closing this.

**Closed by mpociot** 2023-08-17 09:20 UTC

**Comment by eborio** [comment] 2023-10-04 02:33
I have the same problem. I receive the Content-Type header as text/html; charset=UTF-8 when I am using response()->json().

On a web server it works perfectly, but locally I have this situation.

**Comment by thanoseleftherakos** [comment] 2023-11-29 14:11
Same problem here. Has anyone identified the issue?

**Comment by brain82** [comment] 2023-11-29 14:45
@thanoseleftherakos I haven't
