### ISSUE TITLE
[Bug]: psql not linked in herd's bin dir on Windows

### ISSUE THREAD

**Issue by nie7321** [beyondcode/herd-community#1133] opened 2024-11-05 14:48 UTC
### Platform

Windows

### Operating system version

Windows 10

### System architecture

Intel (x86)

### Herd Version

1.11.2

### PHP Version

PHP 8.3

### Bug description

On MacOS, after installing Postgres, the `psql` command is linked in the bin folder. This puts the correct `psql` command into my `$PATH`.

On Windows, the `psql` command is in `~/.config/herd/bin/services/postgresql/16/bin`. This is not part of the `$PATH`, which makes scripting things like creating DBs harder.

It would be ideal for herd to include the binary in the `$PATH` on all supported OSes. This makes supporting a heterogeneous environment easier.

### Steps to reproduce

Install Herd, activate pro, and install a postgres service. On MacOS, post-install, run `psql`. On Windows, post-install, run `psql`. Note the different results.

**Comment by sschlein** [comment] 2024-11-12 09:18
Thanks, I am closing this because it's a duplicate of https://github.com/beyondcode/herd-community/issues/1060

**Closed by sschlein** 2024-11-12 09:18 UTC
Labels: windows, macOS
