### ISSUE TITLE
[Bug]: I am seeing a small window MenuBarAPP Settings as attached in screen shot after update to 15.0 Beta 

### ISSUE THREAD

**Issue by fakharkhan** [beyondcode/herd-community#802] opened 2024-06-14 08:52 UTC
### Platform

macOS

### Operating system version

15.0 Beta (24A5264n)

### System architecture

Intel (x86)

### Herd Version

1.7.1 (Build:28)

### PHP Version

PHP 8.2

### Bug description

<img width="610" alt="image" src="https://github.com/beyondcode/herd-community/assets/1877752/e8cee56a-5545-4895-be2d-299a9fec6a0f">

**Comment by sschlein** [comment] 2024-06-14 09:01
Duplicate of https://github.com/beyondcode/herd-community/issues/799

**Closed** 2024-06-14 09:02 UTC
Labels: macOS, macOS Sequoia support
