### ISSUE TITLE
[Bug]: Herd crashes when running tests with Dumps enabled

### ISSUE THREAD

**Issue by ConnySjoblom** [beyondcode/herd-community#1016] opened 2024-09-20 10:12 UTC
### Platform

macOS

### Operating system version

15.0

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.0

### PHP Version

8.3.11

### Bug description

Herd crashes when running tests if anything is tracked with "Dumps".

(Should Dumps catch anything by default when running tests?)

### Steps to reproduce

1. Enable "Queries" in Dumps
2. Run tests

**Comment by mpociot** [comment] 2024-09-20 10:13
I'm closing this as it's a duplicate of #985 and we keep track of this bug there 👍

**Closed by mpociot** 2024-09-20 10:13 UTC
Labels: macOS
