### ISSUE TITLE
[Bug]: Slow Responses/Rendering even dough BE is fast

### ISSUE THREAD

**Issue by SahinU88** [beyondcode/herd-community#786] opened 2024-06-10 05:42 UTC
### Platform

macOS

### Operating system version

macOS Sonoma 14.5 - Apple M2 Max

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.6.1 (Build: 25)

### PHP Version

PHP 8.2.19 (cli) (built: May 13 2024 09:58:46) (NTS)

### Bug description

It seems like even though requests are processed in a normal speed the response or the loading of the response takes a couple of second every X-requests.

I couldn't figure out specifically if it occurs on certain occasions. At the moment I am trying to collect some information and if it occurs again I am happy to provide some numbers. I am running telescope in the background.

For my setup:

- not sure if relevant but I switched from sail to herd
- valet is installed
- have a mysql installation with brew but the service is not running

Not sure if I have anything else which could cause that.

Here is the tweet I made just as a reference
https://twitter.com/seb_sebsn/status/1799354964382458298

### Steps to reproduce

n.a.

### Relevant log output

```shell
n.a.
```

**Comment by mpociot** [comment] 2024-08-09 09:48
Did this error still occur for you?
I don't think this is a general issue as it seems to fine for many other users though, so I'd close this. I was also unable to reproduce this.

If you happen to come up with a reproducible way for this issue, feel free to reopen it.

**Closed by mpociot** 2024-08-09 09:48 UTC
Labels: macOS

**Comment by SahinU88** [comment] 2024-08-09 12:17
@mpociot thx for the comment.

It's a bit hard to "reproduce" because it's basically present all the time. can I provide any additional information which would help?

the only thing I noticed is that it's only slow and occures every x-requests during the `npm run dev` with inertiajs (react). if I build the frontend with `npm run build` everything seems fine. nothing else I noticed unfortunately

**Comment by SahinU88** [comment] 2024-11-11 10:02
Just for the record. I resolved this issue by uninstalling herd completely and installing it fresh from scratch. now everything works as expected.

I couldn't find any details dough what the issue could have been.
