### ISSUE TITLE
[Bug]: failed to start herd helper service

### ISSUE THREAD

**Issue by rahulsync** [beyondcode/herd-community#566] opened 2024-03-29 14:33 UTC
### Platform

Windows

### Operating system version

Windows 11 Pro

### System architecture

Intel (x86)

### Herd Version

1.0.1

### Bug description

I'm getting the said error while installing the setup file. Please Note I Have **x64 Processor (i7 14700K)**

**Comment by lvltech-mx** [comment] 2024-04-01 18:30
i have the same issue, the herd helper service dont start and i tried everything i can...

**Comment by kimett** [comment] 2024-04-01 21:48
Same issue
Installed 1.0.1 today. Created a new site and opened in browser and nothing. nginx serving ok at 127.0.0.1 and responding with 404
Not anything in windows logs on this. Looks like nvm.exe also fails
`[-](https://github.com/beyondcode/herd-community/issues/566#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/beyondcode/herd-community/issues/566#) <System>
  <Provider Name="PowerShell" /> 
  <EventID Qualifiers="0">403</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>4</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-04-01T21:37:47.8907863Z" /> 
  <EventRecordID>4353</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="39628" ThreadID="0" /> 
  <Channel>Windows PowerShell</Channel> 
  <Computer>play</Computer> 
  <Security /> 
  </System>
[-](https://github.com/beyondcode/herd-community/issues/566#) <EventData>
  <Data>Stopped</Data> 
  <Data>Available</Data> 
  <Data>NewEngineState=Stopped PreviousEngineState=Available SequenceNumber=15 HostName=ConsoleHost HostVersion=5.1.22621.2506 HostId=d3bb07b2-acac-4eab-9622-4ab756d098ba HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy Bypass -Command Restart-Service -Name HerdHelper EngineVersion=5.1.22621.2506 RunspaceId=300001a0-c1b1-4a27-84a5-0f70353f08c7 PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine=</Data> 
  </EventData>
  </Event>`

**Comment by sschlein** [comment] 2024-04-03 14:28
What happens if you run `sc.exe query HerdHelper`from your terminal?

If it detects the service but the state is not "RUNNING", can you try running it via a powershell with admin priviledges:

`sc.exe start HerdHelper`

Is there an error? You can also open Herd, go to the General settings and set it to a different port? It sounds like  port 5000 is already in use.

**Comment by kimett** [comment] 2024-04-03 16:46
Found the issue. Port 5000 is occupied by vmms.exe. I tried a different port my first run and hit another used one.

to check use` netstat -ab` to see used ports in win 11. Should be possible to get an non-used port from the OS programmatically instead of the user trying to debug what happens as an improvement

After selecting a unused port HerdHelper is now green in the settings pane but still can't use the FQDN to open the web app. Don't know where to look for logs from HerdHelper if it has issues with or even trying to update the host definitions

**Comment by GeorgThomassen** [comment] 2024-04-05 11:19
When I try to start the service in services.msc I get an:

> Windows could not start the Herd Helper service on Local Computer. Error 193: 0xc1.

When I look in the Event Viewer it says:

> The Herd Helper service failed to start due to the following error: 
> Herd Helper is not a valid Win32 application.

**Comment by sschlein** [comment] 2024-04-05 12:06
@GeorgThomassen That sounds super odd, which Windows version do you run? It might need a new install as the exe could be broken

@kimett This might be an improvement for a future update that we'll take into account. The helper itself only writes to your hosts file, so in theory you can ann all sites there manually:

```
127.0.0.1 your-site.test
127.0.0.1 your-other-site.test
etc
```

The HerdHelper also writes all directorsy from your parked paths as well as all linked sites to the hosts file, so once you get it up and running, everything should be there after a restart of herd or after changing a directory name in a parked path.

**Comment by andriizaiets** [comment] 2024-04-21 18:11
Same problem, the service starts and stops at the same moment, with no error:
![Screenshot 2024-04-21 210428](https://github.com/beyondcode/herd-community/assets/10029678/f51ae259-9b04-4bb1-9976-f57aebbf706a)
![Screenshot 2024-04-21 210450](https://github.com/beyondcode/herd-community/assets/10029678/f3175a53-023d-4867-b0b1-e67d8416837b)

Manually adding entries to the **hosts** file helped.

**Comment by inventor7** [comment] 2024-05-05 11:47
@sschlein i tried ur suggestion here's what i got : 
![image](https://github.com/beyondcode/herd-community/assets/63302853/90ed57d0-43f7-4533-9a37-ad57243e8d07)

and when i try to change the port with administrator prievlieges it logs an error when changing it.

**Comment by devfastated** [comment] 2024-05-16 22:25
Ive installed herd today and I got the same issue

**Comment by amhassen97** [comment] 2024-05-18 14:00
> @GeorgThomassen That sounds super odd, which Windows version do you run? It might need a new install as the exe could be broken
> 
> @kimett This might be an improvement for a future update that we'll take into account. The helper itself only writes to your hosts file, so in theory you can ann all sites there manually:
> 
> ```
> 127.0.0.1 your-site.test
> 127.0.0.1 your-other-site.test
> etc
> ```
> 
> The HerdHelper also writes all directorsy from your parked paths as well as all linked sites to the hosts file, so once you get it up and running, everything should be there after a restart of herd or after changing a directory name in a parked path.

 I installed Herd today and had the same issue where a new Laravel app could not connect when starting up in the browser. The HerdHelper service status indicator indicates red - as in the screenshot - so I asssumed it wasn't running - but checking the services under Task Manager indicated it was.
 
 Eventually I had to manually edit the hosts file with the domain `app-name.test` to bind to `127.0.0.1` per your comment and it worked in the browser. Have no idea what's causing the issue.
 
 The status indicator still shows red, even after modifying the hosts file manually. It's quite a frustrating to issue to have as I was going around in circles trying to figure out what was the issue.
 
![image](https://github.com/beyondcode/herd-community/assets/50408869/96eb7fdb-d50f-4633-9a49-9953583d3a97)

**Comment by sschlein** [comment] 2024-05-18 14:24
If the Helper is running but the indicator is red, that means that the Herd app can't connect to the exposed web service of the helper. 

I've a hard time debugging this as we've never been able to reproduce or pin down the issue on our machines. 

In my opinion the most likely reason is a firewall or anti virus issue and we need to find a way to solve this. 

Once the helper is running and the app is able to connect, you could create a new folder in a parked directly or link a project to trigger the write to the hosts file.

**Comment by geomorillo** [comment] 2024-05-24 23:48
im using w10, Ive got no antivirus and im using the default windows firewall,  if i disable it,  it doesnt work either, the indicator is red and
PS C:\WINDOWS\system32> sc.exe query HerdHelper

NOMBRE_SERVICIO: HerdHelper
        TIPO               : 10  WIN32_OWN_PROCESS
        ESTADO             : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        CÓD_SALIDA_WIN32   : 0  (0x0)
        CÓD_SALIDA_SERVICIO: 0  (0x0)
        PUNTO_COMPROB.     : 0x0
        INDICACIÓN_INICIO  : 0x0

**Comment by amhassen97** [comment] 2024-05-25 09:31
Yeah pretty much the same for me, it was on my personal machine

**Comment by amralsaleeh** [comment] 2024-05-25 10:56
Apparently, the firewall was the cause, after it was stopped everything started working normally ✅

**Comment by sschlein** [comment] 2024-05-25 14:20
> Apparently, the firewall was the cause, after it was stopped everything started working normally ✅

Which one do you use?

**Comment by sschlein** [comment] 2024-05-30 11:12
Hey folks, can you please try this debug version?

[Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/Herd-1.6.1-setup_preview.zip)

* Install debug version
* Go to General settings and enable the HerdHelper debug mode
* Restart Herd
* Check the logs (linked at the general settings, click on the path to get there)
* Also check the logs at %USERPROFILE%\AppData\Roaming\Herd\logs

You can either post the logs here or send them to support@beyondco.de (and please mention this issue #566

**Comment by sschlein** [comment] 2024-06-03 09:51
Hey folks, can you please try this NEW debug version?

This one should heal itself it the port is already in use, fix not existing hosts files, write to read-only hosts files and only use IPv6 in cases that this is properly configured on the host machine.

[Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/Herd-1.6.1-latest.exe.zip)

* Install debug version
* Restart Herd
* Also check the logs at %USERPROFILE%\AppData\Roaming\Herd\logs

You can either post the logs here or send them to [support@beyondco.de](mailto:support@beyondco.de)

Thanks for helping us with debugging.

**Comment by Thusatharan** [comment] 2024-06-04 01:36
It looks like the HerdHelper port is causing the issue. The solution for this is to:

1. Navigate to your project folder.
2. Run the command `php artisan serve`

**Comment by kmaphane** [comment] 2024-06-08 17:29
[main.log](https://github.com/user-attachments/files/15749087/main.log)

Hope this helps with debugging the issue.

**Comment by sschlein** [comment] 2024-06-08 17:36
Could you also share the herdhelper log file? Thanks!

**Comment by kmaphane** [comment] 2024-06-08 17:53
> Could you also share the herdhelper log file? Thanks!

The log I sent above is from this file path: %USERPROFILE%\AppData\Roaming\Herd\logs

I have nothing in this file path from Herd:  C:\Windows\System32\logs.  I have enabled it though 

![image](https://github.com/beyondcode/herd-community/assets/80934965/d1686dd0-b769-4a7e-8e97-4215968ffd85)

the only log I have from this file path had to do nginx which I resolved: %USERPROFILE%\.config\herd\Log

**Comment by bytesandcode** [comment] 2024-06-11 07:27
I am facing the same issue, here is something that I have got in logs:

2024-06-10 21:56:19.976 +05:30 [INF] IPv6 is supported. Added http://[::1]:5000/ to listener prefixes.
2024-06-10 21:56:19.990 +05:30 [ERR] An error occurred while starting the HTTP server: The network location cannot be reached. For information about network troubleshooting, see Windows Help.
2024-06-10 21:56:19.991 +05:30 [ERR] An error occurred: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
2024-06-10 21:56:19.993 +05:30 [ERR] BackgroundService failed
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.Stop()
   at HerdHelper.Worker.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2024-06-10 21:56:20.027 +05:30 [FTL] The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.Stop()
   at HerdHelper.Worker.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2024-06-10 21:56:20.028 +05:30 [INF] Application is shutting down...
2024-06-10 21:56:20.029 +05:30 [DBG] Hosting stopping
2024-06-10 21:56:20.037 +05:30 [DBG] Hosting stopped

**Comment by bytesandcode** [comment] 2024-06-11 08:56
Windows does not have dnsmasq, can this be causing issues?

**Comment by sschlein** [comment] 2024-06-11 09:00
No, this is why we have this service that writes to your hosts file instead of using dnsmasq 🙂

Did you try other ports? It seems that something is blocking the service from starting up and opening the port so that the Herd app an access the helper service. Any firewall or anti virus software that could cause this?

**Comment by bytesandcode** [comment] 2024-06-12 07:27
I have tried using different ports and disabling the firewall, but nothing works. It appears that the service responsible for writing domains to the hosts file is not functioning correctly. I manually added the IP address (127.0.0.1) and the domain (example.test) to the hosts file. Wildcards (*.test) are not supported too in the hosts file. So, the only option is to write all the domains manually.

**Comment by sschlein** [comment] 2024-06-12 09:12
@bytesandcode 

would you please try this Helper? [Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/HerdHelper_no_ipv6.zip)

You can do that by replacing the HerdHelper.exe from %USERPROFILE%.config\herd\bin with the one from the download. You might need to stop the service first before you can do that, use the commands below.

Please open a powershell with admin permissions to stop and start the helper:

```
sc.exe stop HerdHelper
//replace the exe file
sc.exe start HerdHelper
```

After that, the HerdHelper should either turn green in Herd or at least give us a new herdhelper logfile with more information. The logs are at `C:\Windows\System32\logs` again.

**Comment by bytesandcode** [comment] 2024-06-12 10:04
[herdhelper20240612.txt](https://github.com/user-attachments/files/15802783/herdhelper20240612.txt)
Here is the log file. The status is still red. Here is output from PowerShell:
PS C:\Windows\system32> sc.exe stop HerdHelper

SERVICE_NAME: HerdHelper
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 3  STOP_PENDING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
PS C:\Windows\system32> sc.exe start HerdHelper

SERVICE_NAME: HerdHelper
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x7d0
        PID                : 15484
        FLAGS              :
PS C:\Windows\system32>

**Comment by sschlein** [comment] 2024-06-12 11:30
What happens if you open [127.0.0.1:5000/status](http://127.0.0.1:5000/status) or [localhost:5000/status](http://localhost:5000/status)?

**Comment by bytesandcode** [comment] 2024-06-13 05:47
503, Service Unavailable! But http://127.0.0.1/example.test works.

**Comment by sschlein** [comment] 2024-06-13 07:14
@bytesandcode 

Could you do me a favor?

`sc.exe squery HerdHelper`

This should display this:

```
SERVICE_NAME: HerdHelper
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

You can also verify this with your windows services (sorry German screenshot):
![CleanShot 2024-06-13 at 09 11 05](https://github.com/beyondcode/herd-community/assets/2911113/d7d72d53-a2e7-43c4-8504-9ce62e8cf47b)

The logs of the helper at `C:\Windows\System32\logs` should be like this:

```
2024-06-13 09:08:15.523 +02:00 [INF] Request to /status endpoint.
2024-06-13 09:08:33.229 +02:00 [INF] Application is shutting down...
2024-06-13 09:08:33.233 +02:00 [DBG] Hosting stopping
2024-06-13 09:08:33.261 +02:00 [INF] HTTP Server stopped.
2024-06-13 09:08:33.273 +02:00 [DBG] Hosting stopped
2024-06-13 09:09:22.049 +02:00 [DBG] Hosting starting
2024-06-13 09:09:22.154 +02:00 [INF] Config path: C:\ProgramData\Herd\service.json.
2024-06-13 09:09:22.158 +02:00 [INF] Config file with port exists, using port: 5000.
2024-06-13 09:09:22.166 +02:00 [INF] Application started. Hosting environment: Production; Content root path: C:\Users\seb\.config\herd\bin\
2024-06-13 09:09:22.169 +02:00 [DBG] Hosting started
2024-06-13 09:09:22.193 +02:00 [INF] HTTP Server started on http://localhost:5000/.
2024-06-13 09:09:24.738 +02:00 [INF] Request to /status endpoint.
```

If you go to [127.0.0.1:5000/status](http://127.0.0.1:5000/status), a new line with the request to the status endpoint should be available.

I checked the code 10 times again, and the helper does not return 503 for any request, so I am not even sure that you are hitting the helper and not some other service on your machine...

**Comment by bytesandcode** [comment] 2024-06-13 12:43
PS C:\Windows\system32> sc.exe query HerdHelper

SERVICE_NAME: HerdHelper
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
PS C:\Windows\system32>

![image](https://github.com/beyondcode/herd-community/assets/34193886/d42aa54b-1be5-43e0-944a-8a2e1f391f81)

![image](https://github.com/beyondcode/herd-community/assets/34193886/8f1ab374-fdb1-4d7e-aaa3-f92e56b74cd6)

It shows Herd Helper is Running, but the status is still red. I think I am currently fine with manually adding the domain to the Hosts file.

**Comment by bytesandcode** [comment] 2024-06-13 14:20
Yes, here you go:
2024-06-13 17:24:06.085 +05:30 [DBG] Hosting starting
2024-06-13 17:24:06.292 +05:30 [INF] Config path: C:\ProgramData\Herd\service.json.
2024-06-13 17:24:06.302 +05:30 [INF] Application started. Hosting environment: Production; Content root path: C:\Users\mohdr\.config\herd\bin\
2024-06-13 17:24:06.305 +05:30 [DBG] Hosting started
2024-06-13 17:24:06.307 +05:30 [INF] Config file with port exists, using port: 5000.
2024-06-13 17:24:06.428 +05:30 [INF] HTTP Server started on http://localhost:5000/.

**Comment by sschlein** [comment] 2024-06-13 14:45
Could you try port 5001, 5002, 5014 or some other than 5000? The helper should handle that by itself usually but in case that doesn't work on your machine, I just assume that 5000 is already blocked and we can't detect that properly.

**Comment by itkhansunny** [comment] 2024-06-14 15:31
It's work when i change port, But when i restart my pc then same problem, and ask me to change port

Please fix as soon as you can

**Comment by sschlein** [comment] 2024-06-17 08:18
Does it reset to the default port or does it keep the new port but doesn't work after restart again?

**Comment by sschlein** [comment] 2024-06-19 06:46
Could you restart herd once or create a new site in a parked directory? Is there a directory with the name example in your Herd folder where you store your sites?

**Comment by sschlein** [comment] 2024-06-20 06:31
For those who still have issues, it looks like we have a fix!

There is an issue when installing the HerdHelper on SOME machines that doesn't happen in all our testing environments but that solved it for several users via email support:

1. Open regedit
2. Navigate to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HerdHelper
3. Double click on the "ImagePath" key and edit it, so that its wrapped in double quotes

![10988432b7af5a54c2eaba3776539ac1](https://github.com/beyondcode/herd-community/assets/2911113/6243374a-3496-4a63-8215-4be5ee8beed7)

Then restart the helper service via your Services Windows in Windows or do `sc.exe start herdHelper` from a Powershell with admin permissions.

**Comment by bytesandcode** [comment] 2024-06-20 13:14
@sschlein It is fixed now, thanks a lot for all the help!

**Comment by amhassen97** [comment] 2024-06-22 09:57
Hey

Been away for a while, but followed the fix steps and updated to the latest version, and it seems to be working now thanks! Really appreciate the response and fixes!

**Comment by mpociot** [comment] 2024-06-25 15:02
This should finally be fixed in 1.8.0 🤞

**Closed by mpociot** 2024-06-25 15:02 UTC
Labels: fixed-in-next-release, windows

**Comment by najbo** [comment] 2025-02-20 16:03
Hi @mpociot , sorry to add some stuff here.

I had the same error on my Windows 10 machine (on a domain). My current user in a non-admin ; I also installed Herd with that account (it asks then an elevetated user account during installation, what is normal behavior).

After the installation (latest 1.15.0 release), it shows the error "HerdHelper is installed but not reached". And of course, my C:\users\john-doe-not-an-admin\.config\herd\bin folder has no HerdHelper.exe file. I can find this one in my C:\users\MrAdmin\.config\herd\bin folder ...

And yes, HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HerdHelper points to the user admin .config folder. Which can't be reached from my non-admin session ;-)

How to solve this issue ?

**Comment by emilanderss0n** [comment] 2025-03-04 01:24
I do also have this message and can't create new sites within the app. Windows 11, "ImagePath" key URL is wrapped in double quotes by default for me in regedit.

**Comment by sschlein** [comment] 2025-03-04 07:48
We actually don't have a solution for this right now but I wonder if the HerdHelper windows service is available if you open your Windows Services settings and if you can start it from there – or if you can start a terminal session with admin permissions and run `sc.exe start HerdHelper` to start the service 🤔

**Comment by najbo** [comment] 2025-03-05 08:02
Here's what I did to resolve this issue on a Windows PRO machine, connected to a domain (current user has no admin rights).

1. Uninstall Herd application
2. Remove c:\%USERPROFILE%\.config\herd folder (or rename to backup_herd for example)
3. Remove c:\[YOUR ADMIN USER]\.config\herd folder (this need an admin elevated CLI ; change to the correct admin account name)
4. Check if Service "Herd Helper" has also been deleted ; if not, delete manualy with sc.exe delete HerdHelper or something like that.
5. Reboot your machine
6. Reinstall Herd ; I got again the message "Failed to start the Herd Helper service" at the end of the installation. Don't loose faith.
7. Reboot your machine again.



Et voilà.

**Comment by mpociot** [comment] 2025-03-05 10:51
@najbo I don't really understand your fix.
If I understand it correctly, you basically just uninstall Herd and re-install it? I don't really understand how this changes the behaviour how Herd installs and manages the service 😅

**Comment by najbo** [comment] 2025-03-05 11:16
@mpociot, the issue with HerdHelper was never fixed after a Herd update. I installed Herd from the first version, maybe something was changed later, with user rights or so ?

I just can say that it works now after reinstalling version 1.17.0.
