### ISSUE TITLE
[Bug]: Helper won't run on port 5000 automatically and have to run manually but still can't run [mysite] .test on browser

### ISSUE THREAD

**Issue by JayChristofel** [beyondcode/herd-community#750] opened 2024-05-18 07:56 UTC
### Platform

Windows

### Operating system version

Windows 10 Pro

### System architecture

Windows

### Herd Version

1.6.1 (already updated from 1.1.0)

### PHP Version

PHP 8.2.12 (cli) (built: Oct 24 2023 21:15:15), Herd PHP Version 8.3

### Bug description

I have an issue with Herd,
I can't access my sites .test from Herd to Browser

1. NGINX already on but HerdHelper indicator inactive
2. When Im installed Herd on my laptop, HerdHelper Port indicator still red
3. My HerdHelper must be manually activated and then that thing can activated (cannot activate automatically)
4. I can't access my .test sites using "Open in Browser" action button
5. Node JS cannot be installed using Herd, even i already have it
6. already re-installed 3 times
7. already update but still not works

![images (4)](https://github.com/beyondcode/herd-community/assets/44848413/568e61bd-dac2-4265-8352-d930a100722f)
![image](https://github.com/beyondcode/herd-community/assets/44848413/c5f59620-51c8-4f50-8883-518063ecdd9b)
![image (1)](https://github.com/beyondcode/herd-community/assets/44848413/e72c470c-55dc-45ee-b374-bc6e9b642c49)
![image (2)](https://github.com/beyondcode/herd-community/assets/44848413/f7b91a70-fe0f-4703-bba9-695afa486198)
![image (3)](https://github.com/beyondcode/herd-community/assets/44848413/fe369cfb-992d-4bc9-aa80-1d7c1a61b813)
![Screenshot 2024-05-18 144116](https://github.com/beyondcode/herd-community/assets/44848413/8ab6e9b5-d4a9-46f8-ae81-45b5dffc3758)

### Relevant log output

```shell
2024/05/14 16:04:11 [error] 5576#5868: *2 FastCGI sent in stderr: "PHP Fatal error:  Maximum execution time of 30 seconds exceeded in C:\Users\User\Herd\lms\vendor\vlucas\phpdotenv\src\Store\FileStore.php on line 10" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9083", host: "lms.test"
2024/05/14 16:05:02 [error] 7728#11516: *1 FastCGI sent in stderr: "PHP Fatal error:  Maximum execution time of 30 seconds exceeded in C:\Users\User\Herd\lms\vendor\laravel\framework\src\Illuminate\Database\Events\ConnectionEstablished.php on line 5
PHP Fatal error:  Maximum execution time of 30 seconds exceeded in C:\Users\User\Herd\lms\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php on line 25" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9083", host: "lms.test"
```

**Comment by sschlein** [comment] 2024-05-18 11:46
Duplicate of https://github.com/beyondcode/herd-community/issues/727
 🙂

**Closed** 2024-05-18 11:46 UTC
Labels: windows
