### ISSUE TITLE
[Bug]: Call to undefined function openssl_cipher_iv_length

### ISSUE THREAD

**Issue by AndreasFurster** [beyondcode/herd-community#592] opened 2024-04-02 14:52 UTC
### Platform

Windows

### Operating system version

Windows 11 Pro (22H2 22621.3374)

### System architecture

Intel (x86)

### Herd Version

1.0.1

### PHP Version

PHP 8.3.4

### Bug description

With Herd Pro and XDebug enabled, I get the following exception:

Call to undefined function Illuminate\Encryption\openssl_cipher_iv_length() at C:\Users\...\vendor\laravel\framework\src\Illuminate\Encryption\Encrypter.php:250

The exception occurs in the default EncryptCookies middleware. 

The openssl extension is enabled in the php.ini. But when I run phpinfo(), OpenSSL support is disabled under the Phar section. Not sure if that matters.  

### Relevant log output

```shell
[object] (Error(code: 0): Call to undefined function Illuminate\Encryption\openssl_cipher_iv_length() at C:\Users\...\vendor\laravel\framework\src\Illuminate\Encryption\Encrypter.php:250)
[stacktrace]
#0 C:\Users\...\vendor\laravel\framework\src\Illuminate\Encryption\Encrypter.php(217): Illuminate\Encryption\Encrypter->validPayload(Array)
#1 C:\Users\...\vendor\laravel\framework\src\Illuminate\Encryption\Encrypter.php(151): Illuminate\Encryption\Encrypter->getJsonPayload(Array)
#2 C:\Users\...\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(138): Illuminate\Encryption\Encrypter->decrypt('eyJpdiI6Ii92T2t...', false)
#3 C:\Users\...\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(84): Illuminate\Cookie\Middleware\EncryptCookies->decryptCookie('XSRF-TOKEN', 'eyJpdiI6Ii92T2t...')
#4 C:\Users\...\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Cookie\Middleware\EncryptCookies->decrypt(Object(Illuminate\Http\Request))
#5 C:\Users\...\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#6 C:\Users\...\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#7 C:\Users\...\vendor\laravel\framework\src\Illuminate\Routing\Router.php(805): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#8 C:\Users\...\vendor\laravel\framework\src\Illuminate\Routing\Router.php(784): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#9 C:\Users\...\vendor\laravel\framework\src\Illuminate\Routing\Router.php(748): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#10 C:\Users\...\vendor\laravel\framework\src\Illuminate\Routing\Router.php(737): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#11 C:\Users\...\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(200): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 C:\Users\...\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(144): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#13 C:\Users\...\vendor\laravel\
ova\src\Http\Middleware\ServeNova.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 C:\Users\...\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Laravel\Nova\Http\Middleware\ServeNova->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 C:\Users\...\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 C:\Users\...\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 C:\Users\...\vendor\laravel\vapor-core\src\Http\Middleware\ServeStaticAssets.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 C:\Users\...\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Laravel\Vapor\Http\Middleware\ServeStaticAssets->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 C:\Users\...\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 C:\Users\...\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 C:\Users\...\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 C:\Users\...\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\Users\...\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 C:\Users\...\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 C:\Users\...\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\Users\...\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 C:\Users\...\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 C:\Users\...\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 C:\Users\...\vendor\laravel\framework\src\Illuminate\Http\Middleware\HandleCors.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 C:\Users\...\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Http\Middleware\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 C:\Users\...\vendor\laravel\framework\src\Illuminate\Http\Middleware\TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 C:\Users\...\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(183): Illuminate\Http\Middleware\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 C:\Users\...\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 C:\Users\...\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(175): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#35 C:\Users\...\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#36 C:\Users\...\public\index.php(51): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#37 C:\Program Files\Herd\resources\app.asar.unpacked\resources\valet\server.php(135): require('C:\\Users\\andrea...')
#38 {main}
```

**Comment by mechelon** [comment] 2024-04-02 16:49
Duplicate of #565

**Closed by mechelon** 2024-04-02 16:49 UTC
Labels: windows
