### ISSUE TITLE
[Bug]: ini changes not reflected in nginx

### ISSUE THREAD

**Issue by philharmonie** [beyondcode/herd-community#222] opened 2023-10-23 07:54 UTC
### Operating system version

macOS Sonoma 14.0

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1 (Builld: 18)

### PHP Version

PHP 8.2.11 (cli) (built: Sep 29 2023 00:10:16) (NTS)

### Bug description

After updating the php.ini with a different `memory_limit` and restarting herd the CLI does reflect the change but nginx (?) does not.

### Steps to reproduce

I added memory_limit=1G to the php.ini file:
```
echo 'memory_limit=1G' >> /Users/phil/Library/Application\ Support/Herd/config/php/82/php.ini
```
and restarted herd:
```
herd restart
```
The CLI shows the changes successfully:
```
php -i | grep "memory_limit"
memory_limit => 1G => 1G
```
But when I execute "phpinfo();" I see the correct php.ini but the `memory_limit` still shows 512M.

**Comment by mpociot** [comment] 2023-10-23 07:55
Are all Herd Services marked as running?
This could be caused by a stray PHP FPM service that still holds the old ini values.

**Comment by philharmonie** [comment] 2023-10-23 07:56
Yes, all services are running (from what I can see from the GUI menu)

**Comment by almeidafranci** [comment] 2023-10-24 21:22
I am currently having the same issue with a site running in PHP 8.1.

**Comment by almeidafranci** [comment] 2023-10-24 21:26
I was having the same issue with a site running on PHP 8.1. Changing the version to 8.2 and then back to 8.1 made it load the updated php.ini settings.

**Comment by philharmonie** [comment] 2023-10-25 06:23
Can't confirm this is working. I had 8.2 installed only. I added 8.1 and toggled the versions, but the 512M for `memory_limit` stay.
I don't know, if this is related, but the nginx.conf has `client_max_body_size 512M`

**Comment by philharmonie** [comment] 2023-10-25 06:41
I found the solution. The fpm config overrides the php.ini values. There is a setting `php_admin_value[memory_limit] = 512M` in `/Users/user/Library/Application\ Support/Herd/config/fpm/8.2-fpm.conf. Changing that and restarting, fixes the issue.
There is a comment, describing exactly that, but the values are uncommented per default. I don't know, if I like this approach.

**Comment by mpociot** [comment] 2023-10-27 12:47
> I found the solution. The fpm config overrides the php.ini values. There is a setting `php_admin_value[memory_limit] = 512M` in `/Users/user/Library/Application\ Support/Herd/config/fpm/8.2-fpm.conf`. Changing that and restarting, fixes the issue. There is a comment, describing exactly that, but the values are uncommented per default. I don't know, if I like this approach.

Ah you're right. I'll remove those values from the FPM configuration and move them to the php.ini instead. Thanks!

**Closed by mpociot** 2023-10-27 12:47 UTC

**Comment by juddlyon** [comment] 2024-01-15 21:05
I had the same issue as @philharmonie and had to edit the respective PHP FPM configs.

I'm using Herd 1.3.2 on Sonoma 14.2.1.

`memory_limit`, `upload_max_filesize`, and `post_max_size` cannot currently be changed via the Herd UI or editing PHP INI
