### ISSUE TITLE
[Bug]: Cant Create Sites (Rapid Screen Flash)

### ISSUE THREAD

**Issue by JoeOH042** [beyondcode/herd-community#1106] opened 2024-10-22 01:48 UTC
### Platform

macOS

### Operating system version

14.2.1 (23C71)

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.11.1

### Bug description

The product is totally unusable on my Mac. When attempting to add a site the "Choose a template for your new site" prompt appears and flashes repeatedly very fast. No input from keyboard or mouse is accepted. Application is totally unresponsive. 

### Steps to reproduce

Attempting to add a new site

**Comment by mpociot** [comment] 2024-10-22 09:05
Could you provide a screen recording? I have no idea how to reproduce this locally.

**Comment by JoeOH042** [comment] 2024-10-23 01:54
https://github.com/user-attachments/assets/ce5dac07-12cb-440d-bcd4-742208a1f8bc

**Comment by stefandroog** [comment] 2024-10-23 19:05
Duplicate of https://github.com/beyondcode/herd-community/issues/1052

No update at that one as well. This tool is useless (for now).

**Comment by sschlein** [comment] 2024-10-24 07:19
You can create sites via the terminal: https://herd.laravel.com/docs/1/getting-started/sites#creating-your-first-site

You are running an old version of macOS, 14.2 is about a year old. Can you try updating to the latest macOS 14 version if you don't want to move to 15 yet? 14.7 also has the latest security updates.

**Comment by mpociot** [comment] 2024-10-24 08:53
I was just able to reproduce this on macOS 14.0 as well.
The issue does not occur on macOS 14.5+ (I haven't checked every version in-between)
What's interesting is that this bug also does not occur on older macOS versions (like macOS 12).

So this is unfortunately a macOS bug and you should update your OS. I will add a check into Herd to prevent this from happening, but we won't be able to fix the root issue as it's OS related.

**Closed by mpociot** 2024-10-24 08:53 UTC
Labels: macOS
