### ISSUE TITLE
mbregex is not enabled: 

### ISSUE THREAD

**Issue by khairy-pelcro** [beyondcode/herd-community#15] opened 2023-07-22 14:44 UTC
### Operating system version

macOS 13.5

### Herd Version

1.0.8

### PHP Version

PHP 7.4.33 (cli) (built: Jun 22 2023 14:55:58) ( NTS )

### Bug description

When trying Herd with an existing project that uses PHP7.4 and mbregex i got this error
Uncaught Error: Call to undefined function mb_regex_encoding(), I think the problem that PHP built using this option --disable-mbregex

### Steps to reproduce

just try to use this method mb_regex_encoding using php7.4 

### Relevant log output

```shell
Fatal error: Uncaught Error: Call to undefined function mb_regex_encoding()
```

**Comment by mpociot** [comment] 2023-07-22 18:05
Duplicate of #5

**Closed by mpociot** 2023-07-22 18:05 UTC

**Comment by khairy-pelcro** [comment] 2023-07-22 21:37
Thanks for quick reply
