### ISSUE TITLE
[Bug]: Helper won't run on port 5000 or any port

### ISSUE THREAD

**Issue by graememullins** [beyondcode/herd-community#727] opened 2024-05-12 18:49 UTC
### Platform

Windows

### Operating system version

Windows 11

### System architecture

Windows

### Herd Version

1.1.0

### PHP Version

8.3.7

### Bug description

The helper won't run on port 5000, however the service is running in services.
Is there a fix for this, is there anything else I need to do to try another port?

I've tried port 5002, however this still doesn't work.

<img width="477" alt="herd_port" src="https://github.com/beyondcode/herd-community/assets/97401763/9dcc4696-8faf-4580-b861-29ec5f071f9b">
<img width="470" alt="herd_helper" src="https://github.com/beyondcode/herd-community/assets/97401763/a56630bb-d599-4a73-bbd6-0ef5006d8b52">

Also when I go to create a new project, it claims the project is created, however it doesn't get created.

I'm using my own /Projects folder on my D drive to hold any projects, not the herd folder in users.

Graeme

### Steps to reproduce

Re installed Herd 3 times, 
Started and stopped the service Herd Helper.
Windows updates
Herd updates

**Comment by sschlein** [comment] 2024-05-13 10:04
Could you please go to C:\ProgramData\Herd and open the `services.json` and add the debug flag there?

It should look like this:

```
{
	"herdHelperPort": 5000,
	"logLevel": "debug"
}
```

After that, please restart the service.

Then go to `C:\Windows\System32\logs` and open the latest HerdHelper log – if you think there is anything sensitive and you don't want to share it shere, please email it to support@beyondco.de but there should usually just be an indicator if something wasn't able to start.

**Comment by graememullins** [comment] 2024-05-13 13:32
Hi,

I've made these updates and this is the log;

I've just updated my actual username with MYUSERNAME in the below, all other data is the same.

2024-05-13 14:29:49.064 +01:00 [INF] Application is shutting down...
2024-05-13 14:29:49.065 +01:00 [DBG] Hosting stopping
2024-05-13 14:29:49.067 +01:00 [INF] HTTP Server stopped.
2024-05-13 14:29:49.069 +01:00 [DBG] Hosting stopped
2024-05-13 14:29:50.817 +01:00 [DBG] Hosting starting
2024-05-13 14:29:50.865 +01:00 [INF] Config path: C:\ProgramData\Herd\service.json.
2024-05-13 14:29:50.868 +01:00 [INF] Application started. Hosting environment: Production; Content root path: C:\Users\MYUSERNAME\.config\herd\bin\
2024-05-13 14:29:50.869 +01:00 [DBG] Hosting started
2024-05-13 14:29:50.882 +01:00 [INF] Config file with port exists, using port: 5000.
2024-05-13 14:29:50.896 +01:00 [INF] HTTP Server started on http://localhost:5000/.

**Comment by graememullins** [comment] 2024-05-13 19:21
I also have an issue, when I click the plus button in Herd to create a new project, the Laravel installer doesn't run, and just skips to the window which says the project is created.

Does this function also require the helper, are they connected?

<img width="443" alt="herd-site-created-error" src="https://github.com/beyondcode/herd-community/assets/97401763/1950e628-3cbf-4432-80a1-63a5aa650f1e">

**Comment by EGYWEB-Mohamed** [comment] 2024-05-14 00:15
I have had this problem, And I guess the problem caused by an anti-virus app because I wasn't have anti-virus and it was working fine once I install antivirus again it won't work again
am using Kaspersky

**Comment by sschlein** [comment] 2024-05-16 16:12
> I also have an issue, when I click the plus button in Herd to create a new project, the Laravel installer doesn't run, and just skips to the window which says the project is created.
> 
> Does this function also require the helper, are they connected?
> 
> <img alt="herd-site-created-error" width="443" src="https://private-user-images.githubusercontent.com/97401763/330179380-1950e628-3cbf-4432-80a1-63a5aa650f1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzYxNzgsIm5iZiI6MTcxNTg3NTg3OCwicGF0aCI6Ii85NzQwMTc2My8zMzAxNzkzODAtMTk1MGU2MjgtM2NiZi00NDMyLTgwYTEtNjNhNWFhNjUwZjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE2MTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2M2M2YTBjZDk5MWNiZDdkYzFlM2UwZTBhZTYxMDFhNjRlNjBhZTg2NWM3NzMwZDdiMjFiYWJmNzUxNDMwZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._6GlZ4pj310z3i3jtAlOMewkzg1jTMWT8bbuw2wAeuM">

Does your terminal have the `laravel` and `php` binaries available? That usually happens if they are not in your path and Herd can't run `laravel new projectname`

**Comment by graememullins** [comment] 2024-05-16 16:15
It should do, I was using WAMP so would normally create a new project via the terminal.

**Comment by graememullins** [comment] 2024-05-16 16:56
I get Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.14. in phar://C:/Users/MYUSERNAME/.config/herd/bin/laravel.phar/vendor/composer/platform_check.php on line 24

**Comment by sschlein** [comment] 2024-05-16 17:01
It looks like you're running php 8.1 globally but the installer requires php 8.2 because that's the dependency for Laravel 11. 

We definitely need to
Improve the error message but you can get around it by switching to php 8.2 or 8.3 globally. 

Either via the UI or by running `herd use 8.2`

After that, the installier does it's work 🙂

**Comment by graememullins** [comment] 2024-05-16 17:04
Herd claims I'm using 8.3 globally. 
<img width="812" alt="herd-php-global" src="https://github.com/beyondcode/herd-community/assets/97401763/612f7e72-e827-4806-87b0-4acb53104997">

**Comment by sschlein** [comment] 2024-05-16 17:14
It depends what's first in your $PATH variable. I assume that you get 8.1 when you run `php -v`

So my guess is that if you check your PATH variable in your environment variables, herd isn't the first one trying to link php and so it's the old one. That's a. It odd because the installer should place it first 🤔

Do your existing projects work if you clone them into a folder that's parked by herd? That's the one from the general settings.

**Comment by graememullins** [comment] 2024-05-16 17:19
Yeah that command claims 8.1.

<img width="523" alt="herd-php-v" src="https://github.com/beyondcode/herd-community/assets/97401763/e86b7a06-5eec-4bef-8315-e1d2f00e48a0">

My pre-herd projects do work when herd is running and I use the open link, they're all listed now in sites.

**Comment by graememullins** [comment] 2024-05-16 17:34
Wamp was listed in the path, I've removed that and the new projects button works fine now, it's just the issue with herd helper remaining, but for now I can manually create the hosts file record.

**Comment by sschlein** [comment] 2024-05-17 11:19
Regarding the HerdHelper:

Could you please run `sc.exe query HerdHelper` and post the result to verify that it's running?

Does your username contain a space or special chars?

What happens if you change the port? There should be a popup requesting admin priviledges to restart it.

Does the Dumps and Mail features work for those who face the issue but also have Herd Pro?

**Comment by graememullins** [comment] 2024-05-17 14:57
Hi,

This is the results running on port 5000 and 5002.

SERVICE_NAME: HerdHelper
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

When I change the port the pop-up shows but the same issue happens, as shown above I ran the same on port 5002.

Dumps and mail are both green, services with mysql also works fine.

Graeme

**Comment by sschlein** [comment] 2024-05-17 15:46
Could you please mail me the content of your hosts file to our support email address?

**Comment by graememullins** [comment] 2024-05-17 15:56
Hi,

I've just send this over, 

Graeme

**Comment by graememullins** [comment] 2024-05-20 17:04
@sschlein What was the fix for this?

**Comment by sschlein** [comment] 2024-05-20 17:36
It's a duplicate not a permanent fix, sorry.

**Comment by graememullins** [comment] 2024-05-20 18:00
@sschlein Is herd helpers only job to create the URLs in the hosts file? 

I've just been creating them manually for now, and it seems a workaround.

**Comment by sschlein** [comment] 2024-05-20 18:39
Yeah exactly. That's the only thing (writing to your hosts file) that requires admin privileges and using the helper allows us to run all other parts of the app with your normal user account. The helper exposes a rest endpoint that accepts your sites and creates the hosts entries based on that. 

This is why I am wondering what intercepts these calls - for example the status call that displays the information if it's running.

**Comment by graememullins** [comment] 2024-05-20 18:58
Might it work, when you install Herd it tries maybe 5 pre-defined and common free ports.
Only if if fails on all 5, then a workaround option is given?

**Comment by sschlein** [comment] 2024-05-23 07:12
@graememullins and others with the HerdHelper status in red while it's clearly running in your windows services app:

Can you please post the output of:

`sc.exe query HerdHelper`

and then

`curl http://localhost:5000/status` (or your port)

I have no idea why it could start on port 6000 if there is 5000 in your app. Did you try 6000 and then set it back to 5000 but ignored the popup for the restart? Restarting it from the system services or via command line should to the trick.

This needs an admin shell:

```
sc.exe stop HerdHelper
sc.exe start HerdHelper
sc.exe query HerdHelper
```

**Comment by sschlein** [comment] 2024-05-23 13:33
Could you all also do a `ping localhost`, `ping 127.0.0.1` and `ping ::1`?

**Comment by graememullins** [comment] 2024-05-23 16:50
Output of sc.exe query HerdHelper

SERVICE_NAME: HerdHelper
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

curl (port 5002)

{"message": "OK"}

Ping localhost

Pinging PCNAME [::1] with 32 bytes of data:
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms

Ping statistics for ::1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

Ping 127.0.0.1

Pinging 127.0.0.1 with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

Ping ::1

Pinging ::1 with 32 bytes of data:
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms

Ping statistics for ::1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

**Comment by graememullins** [comment] 2024-05-23 16:54
Also;

PS C:\WINDOWS\system32> sc.exe stop HerdHelper

SERVICE_NAME: HerdHelper
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 3  STOP_PENDING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
PS C:\WINDOWS\system32> sc.exe start HerdHelper

SERVICE_NAME: HerdHelper
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x7d0
        PID                : 49896
        FLAGS              :
PS C:\WINDOWS\system32> sc.exe query HerdHelper

SERVICE_NAME: HerdHelper
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
PS C:\WINDOWS\system32>

**Comment by sschlein** [comment] 2024-05-30 11:11
Hey folks, can you please try this debug version? It logs way more data than previous version.

[Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/Herd-1.6.1-setup_preview.zip)

* Install debug version
* Go to General settings and enable the HerdHelper debug mode
* Restart Herd
* Check the logs (linked at the general settings, click on the path to get there)
* Also check the logs at %USERPROFILE%\AppData\Roaming\Herd\logs

You can either post the logs here or send them to support@beyondco.de (and please mention this issue #727

**Comment by graememullins** [comment] 2024-05-31 15:06
When I installed this, I did get a prompt which said, failed to load/start herd helper.

Here it the output from the logs,

2024-05-31 16:03:23.890 +01:00 [DBG] Hosting stopping
2024-05-31 16:03:23.889 +01:00 [INF] Application is shutting down...
2024-05-31 16:03:23.923 +01:00 [INF] HTTP Server stopped.
2024-05-31 16:03:23.927 +01:00 [DBG] Hosting stopped
2024-05-31 16:03:36.465 +01:00 [DBG] Hosting starting
2024-05-31 16:03:36.506 +01:00 [INF] Config path: C:\ProgramData\Herd\service.json.
2024-05-31 16:03:36.507 +01:00 [INF] Config file with port exists, using port: 5000.
2024-05-31 16:03:36.508 +01:00 [INF] Application started. Hosting environment: Production; Content root path: C:\Users\graememullins\.config\herd\bin\
2024-05-31 16:03:36.509 +01:00 [DBG] Hosting started
2024-05-31 16:03:36.522 +01:00 [ERR] BackgroundService failed
System.Net.HttpListenerException (1232): The network location cannot be reached. For information about network troubleshooting, see Windows Help.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at HerdHelper.Worker.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2024-05-31 16:03:36.528 +01:00 [FTL] The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
System.Net.HttpListenerException (1232): The network location cannot be reached. For information about network troubleshooting, see Windows Help.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at HerdHelper.Worker.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2024-05-31 16:03:36.528 +01:00 [INF] Application is shutting down...
2024-05-31 16:03:36.528 +01:00 [DBG] Hosting stopping
2024-05-31 16:03:36.530 +01:00 [DBG] Hosting stopped

**Comment by sschlein** [comment] 2024-06-03 09:51
Hey folks, can you please try this NEW debug version?

This one should heal itself it the port is already in use, fix not existing hosts files, write to read-only hosts files and only use IPv6 in cases that this is properly configured on the host machine.

[Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/Herd-1.6.1-latest.exe.zip)

* Install debug version
* Restart Herd
* Also check the logs at %USERPROFILE%\AppData\Roaming\Herd\logs

You can either post the logs here or send them to [support@beyondco.de](mailto:support@beyondco.de)

Thanks for helping us with debugging.

**Comment by graememullins** [comment] 2024-06-04 15:40
I still get this error;

<img width="369" alt="herd_failed_helper" src="https://github.com/beyondcode/herd-community/assets/97401763/a5b4ea79-4369-4bfa-9ca8-28c40272d124">

**Comment by sschlein** [comment] 2024-06-04 16:43
I wonder why Herd is in C:\Program Files and not C:\Users\USER\AppData\Roaming\Herd 🤔 Is this a Win10 and Win11 difference or why could that happen?

Can you please download this version of the HerdHelper and install it manually? [Download](https://herd-dev.fra1.digitaloceanspaces.com/test-builds/HerdHelper_permission_changer.zip)

To install it manually:

1. Open a powershell as admin
2. Run `sc.exe stop HerdHelper` (if it's there)
3. Replace the HerdHelper.exe in `%USERPROFILE%\.config\Herd\bin`
4. Run `sc.exe start HerdHelper`

If the HerdHelper service can't be started because it's not there yet, please do:

1. `sc.exe create HerdHelper binpath="path-to-HerdHelper.exe"` (should be `C:\Users\YOUR-USER\.config\Herd\bin\HerdHelper.exe`
2. Run `sc.exe start HerdHelper`

This should give us either better error messages during the setup or finally the logs that we need (or a working HerdHelper) at `C:\Windows\System32\logs`

I appreciate your patience and your help to debug this so that we can fix this once and for all.

**Comment by graememullins** [comment] 2024-06-04 17:32
I'm using Win11

I've tried all of the above and get;

SERVICE_NAME: HerdHelper
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x7d0
        PID                : 2216
        FLAGS              :

Logs for you;

2024-06-04 16:38:34.327 +01:00 [DBG] Hosting starting
2024-06-04 16:38:34.378 +01:00 [INF] Config path: C:\ProgramData\Herd\service.json.
2024-06-04 16:38:34.379 +01:00 [INF] Config file with port exists, using port: 5000.
2024-06-04 16:38:34.380 +01:00 [INF] Application started. Hosting environment: Production; Content root path: C:\Users\graememullins\.config\herd\bin\
2024-06-04 16:38:34.381 +01:00 [DBG] Hosting started
2024-06-04 16:38:34.389 +01:00 [INF] IPv6 is supported. Added http://[::1]:5000/ to listener prefixes.
2024-06-04 16:38:34.391 +01:00 [ERR] An error occurred while starting the HTTP server: The network location cannot be reached. For information about network troubleshooting, see Windows Help.
2024-06-04 16:38:34.392 +01:00 [ERR] An error occurred: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
2024-06-04 16:38:34.392 +01:00 [ERR] BackgroundService failed
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.Stop()
   at HerdHelper.Worker.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2024-06-04 16:38:34.397 +01:00 [FTL] The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.Stop()
   at HerdHelper.Worker.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2024-06-04 16:38:34.397 +01:00 [INF] Application is shutting down...
2024-06-04 16:38:34.398 +01:00 [DBG] Hosting stopping
2024-06-04 16:38:34.400 +01:00 [DBG] Hosting stopped
2024-06-04 18:25:17.772 +01:00 [DBG] Hosting starting
2024-06-04 18:25:17.820 +01:00 [INF] Config path: C:\ProgramData\Herd\service.json.
2024-06-04 18:25:17.821 +01:00 [INF] Config file with port exists, using port: 5000.
2024-06-04 18:25:17.822 +01:00 [INF] Application started. Hosting environment: Production; Content root path: C:\Users\graememullins\.config\herd\bin\
2024-06-04 18:25:17.823 +01:00 [DBG] Hosting started
2024-06-04 18:25:17.831 +01:00 [INF] IPv6 is supported. Added http://[::1]:5000/ to listener prefixes.
2024-06-04 18:25:17.832 +01:00 [ERR] An error occurred while starting the HTTP server: The network location cannot be reached. For information about network troubleshooting, see Windows Help.
2024-06-04 18:25:17.832 +01:00 [ERR] An error occurred: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
2024-06-04 18:25:17.833 +01:00 [ERR] BackgroundService failed
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.Stop()
   at HerdHelper.Worker.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2024-06-04 18:25:17.838 +01:00 [FTL] The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.Stop()
   at HerdHelper.Worker.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2024-06-04 18:25:17.838 +01:00 [INF] Application is shutting down...
2024-06-04 18:25:17.839 +01:00 [DBG] Hosting stopping
2024-06-04 18:25:17.841 +01:00 [DBG] Hosting stopped
2024-06-04 18:29:39.437 +01:00 [DBG] Hosting starting
2024-06-04 18:29:39.476 +01:00 [INF] Config path: C:\ProgramData\Herd\service.json.
2024-06-04 18:29:39.477 +01:00 [INF] Config file with port exists, using port: 5000.
2024-06-04 18:29:39.477 +01:00 [INF] Application started. Hosting environment: Production; Content root path: C:\Users\graememullins\.config\herd\bin\
2024-06-04 18:29:39.478 +01:00 [DBG] Hosting started
2024-06-04 18:29:39.486 +01:00 [INF] IPv6 is supported. Added http://[::1]:5000/ to listener prefixes.
2024-06-04 18:29:39.488 +01:00 [ERR] An error occurred while starting the HTTP server: The network location cannot be reached. For information about network troubleshooting, see Windows Help.
2024-06-04 18:29:39.488 +01:00 [ERR] An error occurred: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
2024-06-04 18:29:39.488 +01:00 [ERR] BackgroundService failed
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.Stop()
   at HerdHelper.Worker.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2024-06-04 18:29:39.493 +01:00 [FTL] The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.Stop()
   at HerdHelper.Worker.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2024-06-04 18:29:39.493 +01:00 [INF] Application is shutting down...
2024-06-04 18:29:39.494 +01:00 [DBG] Hosting stopping
2024-06-04 18:29:39.496 +01:00 [DBG] Hosting stopped
2024-06-04 18:29:57.618 +01:00 [DBG] Hosting starting
2024-06-04 18:29:57.657 +01:00 [INF] Config path: C:\ProgramData\Herd\service.json.
2024-06-04 18:29:57.658 +01:00 [INF] Config file with port exists, using port: 5000.
2024-06-04 18:29:57.659 +01:00 [INF] Application started. Hosting environment: Production; Content root path: C:\Users\graememullins\.config\herd\bin\
2024-06-04 18:29:57.660 +01:00 [DBG] Hosting started
2024-06-04 18:29:57.668 +01:00 [INF] IPv6 is supported. Added http://[::1]:5000/ to listener prefixes.
2024-06-04 18:29:57.669 +01:00 [ERR] An error occurred while starting the HTTP server: The network location cannot be reached. For information about network troubleshooting, see Windows Help.
2024-06-04 18:29:57.669 +01:00 [ERR] An error occurred: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
2024-06-04 18:29:57.670 +01:00 [ERR] BackgroundService failed
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.Stop()
   at HerdHelper.Worker.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2024-06-04 18:29:57.674 +01:00 [FTL] The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.Stop()
   at HerdHelper.Worker.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2024-06-04 18:29:57.675 +01:00 [INF] Application is shutting down...
2024-06-04 18:29:57.675 +01:00 [DBG] Hosting stopping
2024-06-04 18:29:57.677 +01:00 [DBG] Hosting stopped
2024-06-04 18:30:25.598 +01:00 [DBG] Hosting starting
2024-06-04 18:30:25.637 +01:00 [INF] Config path: C:\ProgramData\Herd\service.json.
2024-06-04 18:30:25.638 +01:00 [INF] Config file with port exists, using port: 5000.
2024-06-04 18:30:25.639 +01:00 [INF] Application started. Hosting environment: Production; Content root path: C:\Users\graememullins\.config\herd\bin\
2024-06-04 18:30:25.640 +01:00 [DBG] Hosting started
2024-06-04 18:30:25.648 +01:00 [INF] IPv6 is supported. Added http://[::1]:5000/ to listener prefixes.
2024-06-04 18:30:25.650 +01:00 [ERR] An error occurred while starting the HTTP server: The network location cannot be reached. For information about network troubleshooting, see Windows Help.
2024-06-04 18:30:25.650 +01:00 [ERR] An error occurred: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
2024-06-04 18:30:25.650 +01:00 [ERR] BackgroundService failed
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.Stop()
   at HerdHelper.Worker.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2024-06-04 18:30:25.655 +01:00 [FTL] The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.Stop()
   at HerdHelper.Worker.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2024-06-04 18:30:25.655 +01:00 [INF] Application is shutting down...
2024-06-04 18:30:25.656 +01:00 [DBG] Hosting stopping
2024-06-04 18:30:25.658 +01:00 [DBG] Hosting stopped
2024-06-04 18:30:29.414 +01:00 [DBG] Hosting starting
2024-06-04 18:30:29.457 +01:00 [INF] Config path: C:\ProgramData\Herd\service.json.
2024-06-04 18:30:29.458 +01:00 [INF] Config file with port exists, using port: 5000.
2024-06-04 18:30:29.459 +01:00 [INF] Application started. Hosting environment: Production; Content root path: C:\Users\graememullins\.config\herd\bin\
2024-06-04 18:30:29.460 +01:00 [DBG] Hosting started
2024-06-04 18:30:29.468 +01:00 [INF] IPv6 is supported. Added http://[::1]:5000/ to listener prefixes.
2024-06-04 18:30:29.470 +01:00 [ERR] An error occurred while starting the HTTP server: The network location cannot be reached. For information about network troubleshooting, see Windows Help.
2024-06-04 18:30:29.470 +01:00 [ERR] An error occurred: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
2024-06-04 18:30:29.471 +01:00 [ERR] BackgroundService failed
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.Stop()
   at HerdHelper.Worker.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2024-06-04 18:30:29.476 +01:00 [FTL] The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.Stop()
   at HerdHelper.Worker.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2024-06-04 18:30:29.476 +01:00 [INF] Application is shutting down...
2024-06-04 18:30:29.476 +01:00 [DBG] Hosting stopping
2024-06-04 18:30:29.479 +01:00 [DBG] Hosting stopped

**Comment by sschlein** [comment] 2024-06-06 09:40
I am closing this issue here because we've moved that to the support inbox and there are other HerdHelper issues for follow up with other users.

**Closed by sschlein** 2024-06-06 09:40 UTC
Labels: needs more information, windows

**Comment by graememullins** [comment] 2024-12-21 18:14
I appear to be having this issue again after a windows update;
<img width="490" alt="helper_issue" src="https://github.com/user-attachments/assets/7f4adef2-3de8-47ef-9b1f-982cc805c7d2" />
